export type NsfwLevel = 'Mild' | 'Medium' | 'Extreme';

export type Prompt = {
  id: number;
  text: string;
  nsfwLevel: NsfwLevel;
};

export const PROMPTS: Prompt[] = [
  // ============================================================================
  // MILD (IDs 1-82) - Openly suggestive: flirty, sexy warm-up (nothing explicit)
  // ============================================================================

  // --- Mild: Flirty Icebreakers ---
  { id: 1, text: "What's the first thing you notice on someone you're attracted to?", nsfwLevel: 'Mild' },
  { id: 2, text: "Describe your type in three words, then look around the room.", nsfwLevel: 'Mild' },
  { id: 3, text: "What's your go-to move when you want someone to notice you?", nsfwLevel: 'Mild' },
  { id: 4, text: "Who was your most embarrassing crush, and what did they have going on?", nsfwLevel: 'Mild' },
  { id: 5, text: "What's the most attractive thing someone can wear?", nsfwLevel: 'Mild' },
  { id: 6, text: "Rate your own flirting skills out of 10, then let the group correct you.", nsfwLevel: 'Mild' },
  { id: 7, text: "What's a compliment that instantly makes you blush?", nsfwLevel: 'Mild' },
  { id: 8, text: "What's the biggest green flag that makes you want someone immediately?", nsfwLevel: 'Mild' },
  { id: 9, text: "Who in this room has the best trouble energy?", nsfwLevel: 'Mild' },
  { id: 10, text: "What's your most shameless way of getting someone's attention?", nsfwLevel: 'Mild' },
  { id: 11, text: "Describe your flirting style: smooth, chaotic, or hopeless?", nsfwLevel: 'Mild' },
  { id: 12, text: "What's the fastest anyone has ever caught your eye?", nsfwLevel: 'Mild' },
  { id: 13, text: "Which emoji do you send when you're actually into someone?", nsfwLevel: 'Mild' },
  { id: 14, text: "What instantly makes you lose interest in someone?", nsfwLevel: 'Mild' },

  // --- Mild: Turn-Ons & Attraction ---
  { id: 15, text: "What's an instant turn-on that has nothing to do with looks?", nsfwLevel: 'Mild' },
  { id: 16, text: "What's the most attractive quality someone can have?", nsfwLevel: 'Mild' },
  { id: 17, text: "Where's your favorite place to be kissed that you'd say out loud?", nsfwLevel: 'Mild' },
  { id: 18, text: "What's a small thing someone does that drives you a little wild?", nsfwLevel: 'Mild' },
  { id: 19, text: "What's the most attractive way someone has ever flirted with you?", nsfwLevel: 'Mild' },
  { id: 20, text: "Confess the celebrity you'd completely embarrass yourself for.", nsfwLevel: 'Mild' },
  { id: 21, text: "What outfit makes you feel the most irresistible?", nsfwLevel: 'Mild' },
  { id: 22, text: "What's the sexiest non-sexy thing someone can do?", nsfwLevel: 'Mild' },
  { id: 23, text: "Describe your dream first kiss in detail.", nsfwLevel: 'Mild' },
  { id: 24, text: "What's your biggest weakness in someone you're attracted to?", nsfwLevel: 'Mild' },
  { id: 25, text: "Who here would you swipe right on with no hesitation?", nsfwLevel: 'Mild' },
  { id: 26, text: "What's the flirtiest text you've ever sent sober?", nsfwLevel: 'Mild' },
  { id: 27, text: "What's the quickest way to make you catch feelings?", nsfwLevel: 'Mild' },
  { id: 28, text: "What body part do you notice first? Be honest.", nsfwLevel: 'Mild' },

  // --- Mild: Sexy This or That ---
  { id: 29, text: "Would you rather be irresistibly hot or unbelievably charming?", nsfwLevel: 'Mild' },
  { id: 30, text: "Would you rather kiss the best kisser here or the best looking?", nsfwLevel: 'Mild' },
  { id: 31, text: "Would you rather always make the first move or always be pursued?", nsfwLevel: 'Mild' },
  { id: 32, text: "Would you rather date someone way too hot or way too into you?", nsfwLevel: 'Mild' },
  { id: 33, text: "Would you rather have your search history or your DMs read aloud?", nsfwLevel: 'Mild' },
  { id: 34, text: "Kiss, marry, avoid: three people the group picks for you.", nsfwLevel: 'Mild' },
  { id: 35, text: "Would you rather be caught staring or caught blushing?", nsfwLevel: 'Mild' },
  { id: 36, text: "Would you rather be someone's fantasy or their favorite mistake?", nsfwLevel: 'Mild' },
  { id: 37, text: "Would you rather get a love letter or a very forward text?", nsfwLevel: 'Mild' },
  { id: 38, text: "Would you rather flirt badly or never flirt at all?", nsfwLevel: 'Mild' },

  // --- Mild: Flirty Dares ---
  { id: 39, text: "Give {{randomOtherPlayer}} your best bedroom eyes for 10 seconds without laughing.", nsfwLevel: 'Mild' },
  { id: 40, text: "Whisper something flirty in {{randomOtherPlayer}}'s ear, or drink 2.", nsfwLevel: 'Mild' },
  { id: 41, text: "Compliment {{randomOtherPlayer}}'s best feature while holding eye contact, or drink.", nsfwLevel: 'Mild' },
  { id: 42, text: "Give {{randomOtherPlayer}} an uninterrupted 15-second compliment about how they look tonight.", nsfwLevel: 'Mild' },
  { id: 43, text: "Sit close on {{randomOtherPlayer}}'s side for the next round, or take 2 drinks.", nsfwLevel: 'Mild' },
  { id: 44, text: "Do your slowest, most seductive walk across the room.", nsfwLevel: 'Mild' },
  { id: 45, text: "Give {{randomOtherPlayer}} a 15-second shoulder rub like you mean it.", nsfwLevel: 'Mild' },
  { id: 46, text: "Look {{randomOtherPlayer}} in the eyes and deliver the smoothest line you've got.", nsfwLevel: 'Mild' },
  { id: 47, text: "Make your sexiest face at {{randomOtherPlayer}} and let them rate it, or drink 2.", nsfwLevel: 'Mild' },
  { id: 48, text: "Slow dance with {{randomOtherPlayer}} to whatever plays next.", nsfwLevel: 'Mild' },
  { id: 49, text: "Whisper which player here you'd least mind being stuck under the mistletoe with.", nsfwLevel: 'Mild' },
  { id: 50, text: "Feed {{randomOtherPlayer}} the next sip of your drink.", nsfwLevel: 'Mild' },
  { id: 51, text: "Trace a slow line down {{randomOtherPlayer}}'s arm, or take 2 drinks.", nsfwLevel: 'Mild' },
  { id: 52, text: "Give {{randomOtherPlayer}} a nickname you'd only use in private.", nsfwLevel: 'Mild' },
  { id: 53, text: "Bite your lip and hold eye contact with {{randomOtherPlayer}} for 10 seconds; first to laugh drinks.", nsfwLevel: 'Mild' },
  { id: 54, text: "Read your last text out loud in your most seductive voice.", nsfwLevel: 'Mild' },
  { id: 55, text: "Let {{randomOtherPlayer}} fix your hair or collar, slowly, or drink 2.", nsfwLevel: 'Mild' },
  { id: 56, text: "Say the most flirtatious thing you can to {{randomOtherPlayer}} with a straight face.", nsfwLevel: 'Mild' },

  // --- Mild: Drink If (Flirty) ---
  { id: 57, text: "Drink if you've got a crush on someone in this room.", nsfwLevel: 'Mild' },
  { id: 58, text: "Drink if you've checked someone out tonight.", nsfwLevel: 'Mild' },
  { id: 59, text: "Take a sip for every person here you'd consider kissing.", nsfwLevel: 'Mild' },
  { id: 60, text: "Drink if you're a shameless flirt once you've had a few.", nsfwLevel: 'Mild' },
  { id: 61, text: "Drink if you've re-read a flirty text just to feel something.", nsfwLevel: 'Mild' },
  { id: 62, text: "Drink if you've ever had a crush on a friend.", nsfwLevel: 'Mild' },
  { id: 63, text: "Drink if you've kissed someone within an hour of meeting them.", nsfwLevel: 'Mild' },
  { id: 64, text: "Drink if you came out tonight secretly hoping to meet someone.", nsfwLevel: 'Mild' },
  { id: 65, text: "Drink if you've got a type and everyone already knows it.", nsfwLevel: 'Mild' },
  { id: 66, text: "Drink if you've ever sent a risky text and instantly regretted it.", nsfwLevel: 'Mild' },
  { id: 67, text: "Anyone who's the flirtiest one in their friend group, drink twice.", nsfwLevel: 'Mild' },
  { id: 68, text: "Drink if you've had a dream about someone in this room.", nsfwLevel: 'Mild' },
  { id: 69, text: "Drink if you'd say yes to a kiss dare right now.", nsfwLevel: 'Mild' },
  { id: 70, text: "Drink if there's someone here you'd let walk you home.", nsfwLevel: 'Mild' },

  // --- Mild: Tension & Reveals ---
  { id: 71, text: "Confess the last time someone made you nervous in a good way.", nsfwLevel: 'Mild' },
  { id: 72, text: "Reveal your most-used pickup line, or drink 2.", nsfwLevel: 'Mild' },
  { id: 73, text: "Describe the best kiss of your life without naming names.", nsfwLevel: 'Mild' },
  { id: 74, text: "Admit which player here you'd want as your spin-the-bottle partner.", nsfwLevel: 'Mild' },
  { id: 75, text: "Tell the group your biggest flirting red flag.", nsfwLevel: 'Mild' },
  { id: 76, text: "Confess a time you embarrassed yourself over someone hot.", nsfwLevel: 'Mild' },
  { id: 77, text: "Say the most flirtatious thing you can to the person on your left.", nsfwLevel: 'Mild' },
  { id: 78, text: "Reveal what someone has to do to instantly win you over.", nsfwLevel: 'Mild' },
  { id: 79, text: "Rate the room's collective flirting game and crown a winner; they give out 2 drinks.", nsfwLevel: 'Mild' },
  { id: 80, text: "Tell {{randomOtherPlayer}} one thing they do that's lowkey attractive.", nsfwLevel: 'Mild' },
  { id: 81, text: "Confess who gave you your most memorable first-kiss story.", nsfwLevel: 'Mild' },
  { id: 82, text: "Reveal how you act when you're into someone: obvious, sneaky, or clueless?", nsfwLevel: 'Mild' },

  // ============================================================================
  // MEDIUM (IDs 100-264) - Overtly sexual: dirty talk, hands-on dares, escalating
  // ============================================================================

  // --- Medium: Dirty Confessions ---
  { id: 100, text: "What's the craziest place you've ever hooked up?", nsfwLevel: 'Medium' },
  { id: 101, text: "Describe your wildest hookup without naming names.", nsfwLevel: 'Medium' },
  { id: 102, text: "What's the dirtiest text you've ever sent? Read it or drink 3.", nsfwLevel: 'Medium' },
  { id: 103, text: "Confess your go-to fantasy, at least the tame version of it.", nsfwLevel: 'Medium' },
  { id: 104, text: "What's the most trouble you've gotten into over hooking up with someone?", nsfwLevel: 'Medium' },
  { id: 105, text: "What's your body count range? Give us hot, cold, or 'no comment' and drink 2.", nsfwLevel: 'Medium' },
  { id: 106, text: "Confess the hottest thing someone has ever said to you in bed.", nsfwLevel: 'Medium' },
  { id: 107, text: "What's the closest you've come to getting caught in the act?", nsfwLevel: 'Medium' },
  { id: 108, text: "Describe your type in bed in one sentence.", nsfwLevel: 'Medium' },
  { id: 109, text: "What's the boldest thing you've done to seduce someone?", nsfwLevel: 'Medium' },
  { id: 110, text: "Confess a hookup you'd absolutely repeat tonight if you could.", nsfwLevel: 'Medium' },
  { id: 111, text: "What's the most spontaneous sex you've ever had?", nsfwLevel: 'Medium' },
  { id: 112, text: "Reveal the wildest place you'd be down to get frisky.", nsfwLevel: 'Medium' },
  { id: 113, text: "What's your favorite thing to do to someone you're into?", nsfwLevel: 'Medium' },
  { id: 114, text: "Confess the last thing you did that would make your mother faint.", nsfwLevel: 'Medium' },
  { id: 115, text: "What's the sexiest dream you've had recently?", nsfwLevel: 'Medium' },
  { id: 116, text: "Describe exactly how you like to be kissed.", nsfwLevel: 'Medium' },
  { id: 117, text: "What's a turn-on you're a little embarrassed about?", nsfwLevel: 'Medium' },
  { id: 118, text: "What's the hottest hookup story your friends know you for?", nsfwLevel: 'Medium' },
  { id: 119, text: "What's your biggest 'I shouldn't, but I would' about someone here?", nsfwLevel: 'Medium' },
  { id: 120, text: "Are you louder or quieter than people would expect? Confess or drink 2.", nsfwLevel: 'Medium' },
  { id: 121, text: "What's the most daring thing you've done somewhere semi-public?", nsfwLevel: 'Medium' },
  { id: 122, text: "Reveal your dirtiest guilty-pleasure fantasy scenario.", nsfwLevel: 'Medium' },
  { id: 123, text: "What's the fastest you've ever gone from flirting to a lot more?", nsfwLevel: 'Medium' },
  { id: 124, text: "Confess the wildest thing you've said yes to in the heat of the moment.", nsfwLevel: 'Medium' },

  // --- Medium: Dirty Questions ---
  { id: 125, text: "What's your favorite part of {{randomOtherPlayer}}'s body? Be specific.", nsfwLevel: 'Medium' },
  { id: 126, text: "Where do you most love being touched?", nsfwLevel: 'Medium' },
  { id: 127, text: "If you had to hook up with one person here, who and why?", nsfwLevel: 'Medium' },
  { id: 128, text: "What's the sexiest thing someone can do with their hands?", nsfwLevel: 'Medium' },
  { id: 129, text: "Dominant or submissive? Prove it or drink 2.", nsfwLevel: 'Medium' },
  { id: 130, text: "What's your ideal way to be woken up by someone?", nsfwLevel: 'Medium' },
  { id: 131, text: "Who in this room gives the best 'take me home' energy?", nsfwLevel: 'Medium' },
  { id: 132, text: "What's an instant turn-on that gets you every single time?", nsfwLevel: 'Medium' },
  { id: 133, text: "What would you do to {{randomOtherPlayer}} if the lights went out for a minute?", nsfwLevel: 'Medium' },
  { id: 134, text: "What's your dirtiest thought right now? Say it or drink 3.", nsfwLevel: 'Medium' },
  { id: 135, text: "Where's the most adventurous place you'd want to try something?", nsfwLevel: 'Medium' },
  { id: 136, text: "What's the quickest way to turn you on without touching you?", nsfwLevel: 'Medium' },
  { id: 137, text: "Who here would you pick for a no-strings night? Point or drink 3.", nsfwLevel: 'Medium' },
  { id: 138, text: "What's your favorite position, in as few words as possible?", nsfwLevel: 'Medium' },
  { id: 139, text: "What's a kink you're at least a little curious about?", nsfwLevel: 'Medium' },
  { id: 140, text: "What sound or word instantly gets you going?", nsfwLevel: 'Medium' },
  { id: 141, text: "If {{randomOtherPlayer}} made a move right now, what's your honest reaction?", nsfwLevel: 'Medium' },
  { id: 142, text: "What's the hottest thing about the person to your left?", nsfwLevel: 'Medium' },
  { id: 143, text: "How do you like it: slow and teasing, or fast and reckless?", nsfwLevel: 'Medium' },
  { id: 144, text: "What's the most attractive thing someone can whisper to you?", nsfwLevel: 'Medium' },
  { id: 145, text: "Who in this room is secretly the freakiest? They drink 3.", nsfwLevel: 'Medium' },
  { id: 146, text: "What's your biggest green light that someone's about to get lucky?", nsfwLevel: 'Medium' },

  // --- Medium: Drink If (Sexual History) ---
  { id: 147, text: "Drink if you've ever fantasized about someone in this room.", nsfwLevel: 'Medium' },
  { id: 148, text: "Take a drink for every person here you've thought about that way.", nsfwLevel: 'Medium' },
  { id: 149, text: "Drink if you've hooked up somewhere you could've been caught.", nsfwLevel: 'Medium' },
  { id: 150, text: "Drink if you've ever faked it convincingly.", nsfwLevel: 'Medium' },
  { id: 151, text: "Drink if you've sent a nude in the last month.", nsfwLevel: 'Medium' },
  { id: 152, text: "Drink if you've had a one-night stand.", nsfwLevel: 'Medium' },
  { id: 153, text: "Drink if you've hooked up with a coworker.", nsfwLevel: 'Medium' },
  { id: 154, text: "Drink if you've had sex somewhere other than a bed.", nsfwLevel: 'Medium' },
  { id: 155, text: "Drink if your body count is higher than people would guess.", nsfwLevel: 'Medium' },
  { id: 156, text: "Drink if you've hooked up with an ex you swore you were done with.", nsfwLevel: 'Medium' },
  { id: 157, text: "Drink if you've had a friends-with-benefits situation.", nsfwLevel: 'Medium' },
  { id: 158, text: "Drink if you've ever sexted at work.", nsfwLevel: 'Medium' },
  { id: 159, text: "Drink if you've gone home with someone the night you met them.", nsfwLevel: 'Medium' },
  { id: 160, text: "Drink if you own a toy within reach of your bed.", nsfwLevel: 'Medium' },
  { id: 161, text: "Drink if you've ever moaned the wrong name.", nsfwLevel: 'Medium' },
  { id: 162, text: "Drink if you've had a crush on someone completely off-limits.", nsfwLevel: 'Medium' },
  { id: 163, text: "Drink if you've got a hookup you can't tell your friends about.", nsfwLevel: 'Medium' },
  { id: 164, text: "Drink if you've hooked up with someone in this friend group.", nsfwLevel: 'Medium' },
  { id: 165, text: "Drink if you've ever recorded, or been recorded.", nsfwLevel: 'Medium' },
  { id: 166, text: "Drink if you've had sex in a car.", nsfwLevel: 'Medium' },
  { id: 167, text: "Drink if you've ever hooked up on a first date.", nsfwLevel: 'Medium' },
  { id: 168, text: "Drink if you've done something tonight you'd deny tomorrow.", nsfwLevel: 'Medium' },
  { id: 169, text: "Drink if you've had a purely physical thing with someone.", nsfwLevel: 'Medium' },
  { id: 170, text: "Anyone who's had a work crush turn into more, drink twice.", nsfwLevel: 'Medium' },
  { id: 171, text: "Drink if there's someone here you'd say yes to right now.", nsfwLevel: 'Medium' },
  { id: 172, text: "Drink if you've hooked up with someone twice in one night.", nsfwLevel: 'Medium' },

  // --- Medium: Sexual Voting & Group Heat ---
  { id: 173, text: "Everyone vote: who's the best kisser in the room? Winner gives out 3.", nsfwLevel: 'Medium' },
  { id: 174, text: "Who here is most likely to be a freak behind closed doors? They drink 3.", nsfwLevel: 'Medium' },
  { id: 175, text: "Vote for who has the best body in the room; they give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 176, text: "Who's most likely to have a secret spicy account? They drink 3, or prove you wrong.", nsfwLevel: 'Medium' },
  { id: 177, text: "Everyone point: who would you most want a lap dance from? They give out 3.", nsfwLevel: 'Medium' },
  { id: 178, text: "Who gives the most 'dangerous to be alone with' energy? They drink 2.", nsfwLevel: 'Medium' },
  { id: 179, text: "Vote for who's most likely to make the first move tonight; they drink 2.", nsfwLevel: 'Medium' },
  { id: 180, text: "Who here has the best lips? Everyone who agrees drinks.", nsfwLevel: 'Medium' },
  { id: 181, text: "Who's the biggest tease in the room? They give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 182, text: "Vote for who'd win a make-out competition; they pick their partner or drink 3.", nsfwLevel: 'Medium' },
  { id: 183, text: "Who's most likely to send a 2am 'you up?' text? They drink 2.", nsfwLevel: 'Medium' },
  { id: 184, text: "Who has the best ass in the room? Winner gives out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 185, text: "Vote for the horniest person here; they finish their drink.", nsfwLevel: 'Medium' },

  // --- Medium: Hands-On Dares ---
  { id: 186, text: "Give {{randomOtherPlayer}} a lap dance for 15 seconds, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 187, text: "Sit on {{randomOtherPlayer}}'s lap for the next two rounds.", nsfwLevel: 'Medium' },
  { id: 188, text: "Whisper the dirtiest thing you're comfortable saying into {{randomOtherPlayer}}'s ear, or drink 3.", nsfwLevel: 'Medium' },
  { id: 189, text: "Grind on {{randomOtherPlayer}} for 10 seconds, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 190, text: "Give {{randomOtherPlayer}} a slow massage from shoulders to lower back, or drink 3.", nsfwLevel: 'Medium' },
  { id: 191, text: "Kiss {{randomOtherPlayer}} on the cheek, neck, or lips, their choice, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 192, text: "Let {{randomOtherPlayer}} whisper where they'd kiss you first, or drink 2.", nsfwLevel: 'Medium' },
  { id: 193, text: "Trace your fingers slowly up {{randomOtherPlayer}}'s arm and neck, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 194, text: "Straddle a chair and give {{randomOtherPlayer}} your best tease, or drink 3.", nsfwLevel: 'Medium' },
  { id: 195, text: "Slow dance with {{randomOtherPlayer}} close enough to feel their heartbeat, or drink 2.", nsfwLevel: 'Medium' },
  { id: 196, text: "Let {{randomOtherPlayer}} run their hands through your hair for 15 seconds, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 197, text: "Give {{randomOtherPlayer}} a soft neck kiss for 5 seconds, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 198, text: "Sit back-to-front on {{randomOtherPlayer}}'s lap for one round, or drink 3.", nsfwLevel: 'Medium' },
  { id: 199, text: "Do a 15-second sexy dance for the group, or finish your drink.", nsfwLevel: 'Medium' },
  { id: 200, text: "Let {{randomOtherPlayer}} feed you a shot from their hand, or drink 2.", nsfwLevel: 'Medium' },
  { id: 201, text: "Let {{randomOtherPlayer}} place your hands wherever they want them for 10 seconds, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 202, text: "Press up against {{randomOtherPlayer}} and slow dance for a full song, or drink 3.", nsfwLevel: 'Medium' },
  { id: 203, text: "Whisper a rating of how good you think {{randomOtherPlayer}} is in bed, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 204, text: "Let {{randomOtherPlayer}} undo one of your buttons, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 205, text: "Give {{randomOtherPlayer}} your best over-the-clothes tease for 10 seconds, or drink 3.", nsfwLevel: 'Medium' },
  { id: 206, text: "Let {{randomOtherPlayer}} pick a spot above the waist to kiss, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 207, text: "Sit thigh-to-thigh with {{randomOtherPlayer}} and describe your ideal night together, or drink 2.", nsfwLevel: 'Medium' },
  { id: 208, text: "Give {{randomOtherPlayer}} a 10-second lap dance facing them, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 209, text: "Let {{randomOtherPlayer}} trace a word on your lower back; guess it or drink 2.", nsfwLevel: 'Medium' },
  { id: 210, text: "Demonstrate your best slow grind on the nearest chair, or finish your drink.", nsfwLevel: 'Medium' },

  // --- Medium: Sexting & Phone ---
  { id: 211, text: "Show the group the last spicy text you sent, or drink 3.", nsfwLevel: 'Medium' },
  { id: 212, text: "Text your latest crush something flirty right now, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 213, text: "Read your dirtiest saved message out loud, or finish your drink.", nsfwLevel: 'Medium' },
  { id: 214, text: "Reveal the name of the last person you sexted, or drink 3.", nsfwLevel: 'Medium' },
  { id: 215, text: "Let {{randomOtherPlayer}} send one flirty emoji to your most recent match, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 216, text: "Reveal how many people you're texting right now, or drink 2.", nsfwLevel: 'Medium' },
  { id: 217, text: "Show your most recent selfie you didn't post, or drink 2.", nsfwLevel: 'Medium' },
  { id: 218, text: "Read your last DM to a crush in your sexiest voice, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 219, text: "Let the group write a flirty text you have to actually send, or finish your drink.", nsfwLevel: 'Medium' },
  { id: 220, text: "Text 'thinking about you' to someone and screenshot the reply, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 221, text: "Reveal the wildest thing in your search history, or drink 3.", nsfwLevel: 'Medium' },

  // --- Medium: Reveals (Incentivized) ---
  { id: 222, text: "Say your body count out loud to give out 3 drinks, or drink 2 to keep it secret.", nsfwLevel: 'Medium' },
  { id: 223, text: "Reveal your kinkiest turn-on to give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 224, text: "Describe your dirtiest fantasy to give out 3 drinks, or drink 2.", nsfwLevel: 'Medium' },
  { id: 225, text: "Admit which player you'd hook up with to give out 3 drinks, or drink 3.", nsfwLevel: 'Medium' },
  { id: 226, text: "Reveal the weirdest place you've had sex to give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 227, text: "Confess your loudest moment in bed to give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 228, text: "Name your ultimate celebrity hall pass and what you'd do, to give out 2 drinks.", nsfwLevel: 'Medium' },
  { id: 229, text: "Describe your ideal one-night stand to give out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 230, text: "Admit a fantasy involving someone in this room to give out 3 drinks, or drink 3.", nsfwLevel: 'Medium' },
  { id: 231, text: "Say the filthiest thing you're willing to; everyone who blushes drinks.", nsfwLevel: 'Medium' },
  { id: 232, text: "Reveal your hard yes and hard no in bed to give out 3 drinks.", nsfwLevel: 'Medium' },

  // --- Medium: Body & Tension ---
  { id: 233, text: "Undo one button or roll up one sleeve; the group decides which, or drink 2.", nsfwLevel: 'Medium' },
  { id: 234, text: "Describe what you're wearing underneath, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 235, text: "Everyone show a little more skin than you were, or drink.", nsfwLevel: 'Medium' },
  { id: 236, text: "Let {{randomOtherPlayer}} guess your most sensitive spot; nod or drink 2.", nsfwLevel: 'Medium' },
  { id: 237, text: "Take off one accessory as seductively as you can, or drink 2.", nsfwLevel: 'Medium' },
  { id: 238, text: "Let the group vote on one item of yours to lose for the round, or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 239, text: "Describe the last time someone left you breathless, or drink 2.", nsfwLevel: 'Medium' },
  { id: 240, text: "Give {{randomOtherPlayer}} your best 'come here' look, or drink 2.", nsfwLevel: 'Medium' },
  { id: 241, text: "Whisper your safe-for-now fantasy to {{randomOtherPlayer}}, or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 242, text: "Let {{randomOtherPlayer}} choose: kiss their cheek or lose a layer.", nsfwLevel: 'Medium' },
  { id: 243, text: "Tell {{randomOtherPlayer}} exactly how you'd start a night alone with them, or drink 3.", nsfwLevel: 'Medium' },
  { id: 244, text: "Do your most convincing moan; the least convincing player drinks.", nsfwLevel: 'Medium' },

  // --- Medium: Sexual Drink Commands ---
  { id: 245, text: "Everyone not wearing underwear, drink twice.", nsfwLevel: 'Medium' },
  { id: 246, text: "Anyone showing a little cleavage or chest, drink.", nsfwLevel: 'Medium' },
  { id: 247, text: "Everyone who's hooked up with someone in this room, drink.", nsfwLevel: 'Medium' },
  { id: 248, text: "Anyone who's thought about a hookup tonight, drink.", nsfwLevel: 'Medium' },
  { id: 249, text: "The horniest person here, be honest, finishes their drink.", nsfwLevel: 'Medium' },
  { id: 250, text: "Everyone who's down to leave with someone tonight, take a sip; no judgment.", nsfwLevel: 'Medium' },
  { id: 251, text: "Anyone who's had sex today, drink 3, lucky you.", nsfwLevel: 'Medium' },
  { id: 252, text: "Everyone who calls themselves a good kisser, prove it or drink 2.", nsfwLevel: 'Medium' },
  { id: 253, text: "The last person here to hook up, drink 3.", nsfwLevel: 'Medium' },
  { id: 254, text: "Anyone with a toy at home, drink twice.", nsfwLevel: 'Medium' },
  { id: 255, text: "Everyone who's ever hooked up with a friend, drink.", nsfwLevel: 'Medium' },
  { id: 256, text: "The person most likely to leave with someone tonight drinks 2 and takes a bow.", nsfwLevel: 'Medium' },
  { id: 257, text: "Anyone who's ever had a hookup in this room's company, drink.", nsfwLevel: 'Medium' },
  { id: 258, text: "Everyone who's flirted with someone here tonight, drink.", nsfwLevel: 'Medium' },
  { id: 259, text: "Anyone who's not wearing a bra right now, drink twice.", nsfwLevel: 'Medium' },
  { id: 260, text: "Everyone who's had a threesome fantasy about anyone here, drink.", nsfwLevel: 'Medium' },
  { id: 261, text: "The person who's checked someone out the most tonight drinks 2.", nsfwLevel: 'Medium' },
  { id: 262, text: "Anyone who'd fail a lie detector about their body count, drink.", nsfwLevel: 'Medium' },
  { id: 263, text: "Everyone who's ever hooked up to get over someone, drink.", nsfwLevel: 'Medium' },
  { id: 264, text: "The best kisser here, by group vote, gives out 3 drinks.", nsfwLevel: 'Medium' },

  // ============================================================================
  // EXTREME (IDs 300-538) - Escalating heat: confessions, dares & explicit play
  // ============================================================================

  // --- Extreme: Explicit Confessions ---
  { id: 300, text: "Describe, in detail, the filthiest thing you've ever done, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 301, text: "What's the kinkiest thing you've tried and would absolutely do again?", nsfwLevel: 'Extreme' },
  { id: 302, text: "Reveal the fantasy you've never said out loud, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 303, text: "Tell the group exactly what you'd do to {{randomOtherPlayer}} if the room were empty, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 304, text: "What's the riskiest place you've ever finished what you started?", nsfwLevel: 'Extreme' },
  { id: 305, text: "Confess the wildest thing you've been talked into in bed.", nsfwLevel: 'Extreme' },
  { id: 306, text: "Name the person in this room you'd break your own rules for, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 307, text: "Describe how you like to be touched, then let {{randomOtherPlayer}} demonstrate, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 308, text: "What's the most people you've been with in a single week? Drink that number if you'd rather not say.", nsfwLevel: 'Extreme' },
  { id: 309, text: "Whisper your dirtiest fantasy to {{randomOtherPlayer}}, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 310, text: "Confess the most scandalous thing on your phone right now, or hand it to {{randomOtherPlayer}} for 30 seconds.", nsfwLevel: 'Extreme' },
  { id: 311, text: "Reveal the roleplay you'd actually want to try, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 312, text: "What are you into that you'd never admit on a first date? Say it or take 3.", nsfwLevel: 'Extreme' },
  { id: 313, text: "Describe the best you've ever had, details not names, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 314, text: "If you've hooked up with anyone in this room, look at them and drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: Drink If (Explicit) ---
  { id: 315, text: "Drink if you've had a threesome; remove a layer if you'd do it again tonight.", nsfwLevel: 'Extreme' },
  { id: 316, text: "Drink if you've ever been tied up, or done the tying.", nsfwLevel: 'Extreme' },
  { id: 317, text: "Drink if you've ever filmed yourself and still have the evidence.", nsfwLevel: 'Extreme' },
  { id: 318, text: "Drink if you've joined the mile-high club.", nsfwLevel: 'Extreme' },
  { id: 319, text: "Drink if you've ever been choked and asked for it harder.", nsfwLevel: 'Extreme' },
  { id: 320, text: "Drink if you've hooked up with two people in the same friend group.", nsfwLevel: 'Extreme' },
  { id: 321, text: "Drink if you've had a friends-with-benefits arrangement end in chaos.", nsfwLevel: 'Extreme' },
  { id: 322, text: "Drink if you've done something in this exact company you'd never confess sober.", nsfwLevel: 'Extreme' },
  { id: 323, text: "Drink if you own a toy within reach of your bed right now.", nsfwLevel: 'Extreme' },
  { id: 324, text: "Drink if you've had a night you genuinely can't remember but heard the reviews.", nsfwLevel: 'Extreme' },
  { id: 325, text: "Drink if you've ever sent a photo you hope never resurfaces.", nsfwLevel: 'Extreme' },
  { id: 326, text: "Drink if there's someone here you've thought about while alone; make eye contact and take one more.", nsfwLevel: 'Extreme' },
  { id: 327, text: "Drink if you've ever kept going after someone walked in.", nsfwLevel: 'Extreme' },
  { id: 328, text: "Drink if you've broken a bed, a chair, or a house rule.", nsfwLevel: 'Extreme' },
  { id: 329, text: "Drink if you've done it somewhere your boss, your landlord, or your mother would object to.", nsfwLevel: 'Extreme' },

  // --- Extreme: Kissing ---
  { id: 330, text: "Kiss {{randomOtherPlayer}} slowly, no drinks to hide behind, or take 2.", nsfwLevel: 'Extreme' },
  { id: 331, text: "Make out with {{randomOtherPlayer}} for 15 seconds while the room counts.", nsfwLevel: 'Extreme' },
  { id: 332, text: "Kiss {{randomOtherPlayer}} like you mean it, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 333, text: "Let {{randomOtherPlayer}} kiss you anywhere above the waist they choose, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 334, text: "Hover your lips over {{randomOtherPlayer}}'s without touching for 20 seconds; first to close the gap wins, the other drinks.", nsfwLevel: 'Extreme' },
  { id: 335, text: "Kiss the last place you'd expect on {{randomOtherPlayer}}, their choice, or take 2.", nsfwLevel: 'Extreme' },
  { id: 336, text: "Demonstrate on {{randomOtherPlayer}} exactly how you like to be kissed, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 337, text: "Pass an ice cube to {{randomOtherPlayer}} using only your mouth.", nsfwLevel: 'Extreme' },

  // --- Extreme: Neck, Marking & Body Kissing ---
  { id: 338, text: "Kiss {{randomOtherPlayer}}'s neck for 15 seconds, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 339, text: "Leave a mark on {{randomOtherPlayer}} somewhere only they'll find later, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 340, text: "Let {{randomOtherPlayer}} kiss a slow trail from your ear to your collarbone, or take 2.", nsfwLevel: 'Extreme' },
  { id: 341, text: "Kiss your way down {{randomOtherPlayer}}'s arm to their fingertips, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 342, text: "Bite {{randomOtherPlayer}}'s earlobe and whisper one thing you'd do to them, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 343, text: "Let {{randomOtherPlayer}} choose one spot above the belt for you to kiss for 10 seconds, or drink 2.", nsfwLevel: 'Extreme' },

  // --- Extreme: Touch, Ice & Body Shots ---
  { id: 344, text: "Take a body shot off {{randomOtherPlayer}}; they pick the spot.", nsfwLevel: 'Extreme' },
  { id: 345, text: "Let {{randomOtherPlayer}} take a body shot off you; you pick the spot, they don't get to argue.", nsfwLevel: 'Extreme' },
  { id: 346, text: "Lick whipped cream off {{randomOtherPlayer}} wherever they dab it, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 347, text: "Run an ice cube across {{randomOtherPlayer}}'s skin using only your mouth; you choose where, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 348, text: "Let {{randomOtherPlayer}} slide a hand slowly up your thigh; you say when to stop, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 349, text: "Explore {{randomOtherPlayer}} with your hands over clothes for 30 seconds, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 350, text: "Suck on {{randomOtherPlayer}}'s finger while holding eye contact, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 351, text: "Let {{randomOtherPlayer}} trace every inch of your neck and arms with their fingertips for a minute, or drink 2.", nsfwLevel: 'Extreme' },

  // --- Extreme: Lap Dances & Grinding ---
  { id: 352, text: "Give {{randomOtherPlayer}} a lap dance for a full song, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 353, text: "Receive a lap dance from {{randomOtherPlayer}} and keep a straight face, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 354, text: "Grind on {{randomOtherPlayer}} for 30 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 355, text: "Straddle {{randomOtherPlayer}} for 30 seconds and whisper what you're thinking, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 356, text: "Sit facing {{randomOtherPlayer}} on their lap for the next two rounds.", nsfwLevel: 'Extreme' },

  // --- Extreme: Stripping & Strip Teases ---
  { id: 357, text: "Remove one item of clothing, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 358, text: "Let {{randomOtherPlayer}} choose which layer you lose, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 359, text: "Give {{randomOtherPlayer}} a strip tease to one full song, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 360, text: "Use only your teeth to take off one piece of {{randomOtherPlayer}}'s clothing, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 361, text: "Strip to your underwear for the next 3 rounds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 362, text: "Swap one item of clothing with {{randomOtherPlayer}} and wear it until your next turn.", nsfwLevel: 'Extreme' },
  { id: 363, text: "Put on a song and let {{randomOtherPlayer}} undo one button, zipper, or clasp per line of the chorus, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 364, text: "Send your top to the middle of the table for the next round, or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Spanking, Restraints & Power ---
  { id: 365, text: "Spank {{randomOtherPlayer}} once, hard, or take 1 drinks.", nsfwLevel: 'Extreme' },
  { id: 366, text: "Let {{randomOtherPlayer}} spank you and count it out loud, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 367, text: "Let {{randomOtherPlayer}} tie your hands with whatever's nearby for the next two rounds, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 368, text: "Pin {{randomOtherPlayer}} against the nearest wall for 15 seconds, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 369, text: "Obey one command from {{randomOtherPlayer}} this round, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 370, text: "Get blindfolded while {{randomOtherPlayer}} plants one kiss somewhere; guess where after, or drink 2.", nsfwLevel: 'Extreme' },
  { id: 371, text: "Get blindfolded and let {{randomOtherPlayer}} guide your hands anywhere above the waist for 20 seconds, or take 2.", nsfwLevel: 'Extreme' },

  // --- Extreme: Simulated & Narrated ---
  { id: 372, text: "Recreate your go-to move on {{randomOtherPlayer}}, fully clothed, for 15 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 373, text: "Simulate your favorite position with {{randomOtherPlayer}} for 15 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 374, text: "Perform a convincing 10-second preview of your bedroom noises, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 375, text: "Whisper a play-by-play of what you'd do to {{randomOtherPlayer}} until they blush or tell you to stop, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 376, text: "Narrate exactly how you'd undress {{randomOtherPlayer}} without touching them, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 377, text: "Demonstrate on {{randomOtherPlayer}}'s neck how you'd start the night if it were just the two of you, or drink 3.", nsfwLevel: 'Extreme' },

  // --- Extreme: Explicit Contact & High Heat ---
  { id: 378, text: "Let {{randomOtherPlayer}} rest a hand wherever they like for a full round; you can move it once, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 379, text: "Lie back and let {{randomOtherPlayer}} kiss from your collarbone to your waistband, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 380, text: "Let {{randomOtherPlayer}} bite you anywhere above the waist they choose, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 381, text: "Demonstrate your best oral technique on a finger, a bottle, or {{randomOtherPlayer}}'s choosing, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 382, text: "Motorboat or be motorboated by {{randomOtherPlayer}}; pick a role, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 383, text: "Let {{randomOtherPlayer}} draw something on your bare stomach, clothing up, or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 384, text: "Give {{randomOtherPlayer}} a 30-second massage anywhere they point, over clothes, or take 2 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Phone & Reveal (Explicit) ---
  { id: 385, text: "Show the group the last risqué photo in your phone, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 386, text: "Text your most recent hookup 'thinking about you' right now; screenshot the send or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 387, text: "Take a photo you'd never post, keep it private, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 388, text: "Let {{randomOtherPlayer}} scroll your camera roll for 15 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 389, text: "Reveal the wildest thing in your nightstand, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 390, text: "Confess the roleplay or scenario that never fails for you, or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Group & Private Escalation ---
  { id: 391, text: "Everyone strips one layer at the same time; last one undressed finishes their drink.", nsfwLevel: 'Extreme' },
  { id: 392, text: "Spin for it: whoever it lands on, make out for 20 seconds or you both take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 393, text: "Take {{randomOtherPlayer}} somewhere private for 3 minutes, or you both finish your drinks.", nsfwLevel: 'Extreme' },
  { id: 394, text: "Get seven minutes alone with {{randomOtherPlayer}}; the group sets the timer, or you both take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 395, text: "Let the group vote on one dare for you and {{randomOtherPlayer}} together; majority rules, no vetoes, or you both finish.", nsfwLevel: 'Extreme' },
  { id: 396, text: "Trade one dare with {{randomOtherPlayer}} that you both actually have to do, or you both finish your drinks.", nsfwLevel: 'Extreme' },
  { id: 397, text: "Kiss the two people beside you, one after the other, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 398, text: "Let the group choose one article of clothing you lose for the rest of the game.", nsfwLevel: 'Extreme' },

  // --- Extreme: Confess or Consequence ---
  { id: 399, text: "Name the two people here you'd pick for a fantasy scenario, and who does what, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 400, text: "Rank the room by who you'd most want to go home with tonight; say it out loud or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 401, text: "Let {{randomOtherPlayer}} ask you any three questions about your sex life; lie once and you both drink.", nsfwLevel: 'Extreme' },
  { id: 402, text: "Let {{randomOtherPlayer}} whisper the filthiest thing they'd do to you; repeat it to the group or drink 3.", nsfwLevel: 'Extreme' },
  { id: 403, text: "Confess the closest you've ever come to a truly wild story, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 404, text: "Tell the group the one thing you'd never say sober, or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Final Escalation ---
  { id: 405, text: "Wear {{randomOtherPlayer}}'s choice of your remaining clothing until your next turn, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 406, text: "Let {{randomOtherPlayer}} decide: lose two layers or do their dare, no questions asked.", nsfwLevel: 'Extreme' },
  { id: 407, text: "Simulate a 15-second slow build with {{randomOtherPlayer}}: clothed, choreographed, committed, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 408, text: "Let {{randomOtherPlayer}} leave one mark on you and choose where; hidden or not, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 409, text: "Give {{randomOtherPlayer}} the most convincing 10-second preview of your best move, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 410, text: "Let the group dare you to do one thing to {{randomOtherPlayer}}; majority rules, or you finish your drink.", nsfwLevel: 'Extreme' },
  { id: 411, text: "Whisper to {{randomOtherPlayer}} the one place you most want to be kissed, then let them decide, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 412, text: "End the round your way: kiss {{randomOtherPlayer}} however you've been wanting to, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Explicit Confessions ---
  { id: 413, text: "Describe the most memorable thing someone's ever done to you in bed, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 414, text: "What's a hard limit you'd secretly renegotiate for the right person?", nsfwLevel: 'Extreme' },
  { id: 415, text: "Confess the wildest place you've ever wanted to be taken, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 416, text: "Tell {{randomOtherPlayer}} the first thing you'd take off them, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 417, text: "What's the most trouble you've ever gotten into over something in the bedroom?", nsfwLevel: 'Extreme' },
  { id: 418, text: "Reveal the fantasy you'd be too shy to ask a partner for, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 419, text: "What's the boldest thing you've ever done to turn someone on?", nsfwLevel: 'Extreme' },
  { id: 420, text: "Confess the loudest you've ever been, and whether the neighbors knew, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 421, text: "Name the celebrity you'd throw all your standards away for, and exactly what you'd do.", nsfwLevel: 'Extreme' },
  { id: 422, text: "What's the quickest you've ever gone from just talking to something a lot more?", nsfwLevel: 'Extreme' },
  { id: 423, text: "Describe your ideal way to be woken up by someone, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 424, text: "Tell the group the most daring thing you've ever texted, word for word, or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Drink If (Explicit) ---
  { id: 425, text: "Drink if you've hooked up somewhere semi-public and got away with it.", nsfwLevel: 'Extreme' },
  { id: 426, text: "Drink if you've ever left marks on someone, or been left with them.", nsfwLevel: 'Extreme' },
  { id: 427, text: "Drink if you've ever used ice, wax, or something hotter or colder than expected.", nsfwLevel: 'Extreme' },
  { id: 428, text: "Drink if you've had a hookup last until sunrise.", nsfwLevel: 'Extreme' },
  { id: 429, text: "Drink if you've ever done a striptease for someone in private.", nsfwLevel: 'Extreme' },
  { id: 430, text: "Drink if you've ever kept a souvenir from a hookup.", nsfwLevel: 'Extreme' },
  { id: 431, text: "Drink if you've sent a photo you'd panic about if it ever leaked.", nsfwLevel: 'Extreme' },
  { id: 432, text: "Drink if you've ever hooked up to a specific song on purpose.", nsfwLevel: 'Extreme' },
  { id: 433, text: "Drink if you've done something tonight you'd deny in the morning.", nsfwLevel: 'Extreme' },
  { id: 434, text: "Drink if you've ever played a character to spice things up.", nsfwLevel: 'Extreme' },
  { id: 435, text: "Drink if you've ever been the loud one and had to be shushed.", nsfwLevel: 'Extreme' },
  { id: 436, text: "Drink if you've had a hookup so good you texted a friend about it immediately.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Kissing & Necking ---
  { id: 437, text: "Kiss {{randomOtherPlayer}} the way you'd kiss someone you'd waited all night for, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 438, text: "Give {{randomOtherPlayer}} three kisses, each somewhere different above the shoulders, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 439, text: "Let {{randomOtherPlayer}} decide how long your next kiss lasts, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 440, text: "Kiss {{randomOtherPlayer}} slowly while the group counts to ten, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 441, text: "Trade one lingering kiss with {{randomOtherPlayer}}, eyes open the whole time, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 442, text: "Let {{randomOtherPlayer}} guide your chin and kiss you however they like, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 443, text: "Whisper a countdown into {{randomOtherPlayer}}'s ear, then kiss them on zero, or drink 3.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Marking & Body Kissing ---
  { id: 444, text: "Leave a slow kiss along {{randomOtherPlayer}}'s jaw, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 445, text: "Kiss the inside of {{randomOtherPlayer}}'s wrist and work your way up to the elbow, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 446, text: "Let {{randomOtherPlayer}} choose a spot on your shoulders or back to mark, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 447, text: "Kiss {{randomOtherPlayer}}'s neck and tell them exactly what you're thinking, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 448, text: "Let {{randomOtherPlayer}} press their lips just below your ear for ten seconds, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 449, text: "Give {{randomOtherPlayer}} a kiss that starts at the cheek and ends somewhere braver, or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Touch, Ice & Food ---
  { id: 450, text: "Run a single ice cube from {{randomOtherPlayer}}'s collarbone to wherever they allow, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 451, text: "Let {{randomOtherPlayer}} feed you something using only their fingers, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 452, text: "Trace slow circles on {{randomOtherPlayer}}'s lower back for 20 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 453, text: "Let {{randomOtherPlayer}} guide your hands to show you exactly how they like to be held, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 454, text: "Take a shot from {{randomOtherPlayer}}'s collarbone with no hands, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 455, text: "Let {{randomOtherPlayer}} drip a little of their drink and lick it off your wrist, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 456, text: "Let {{randomOtherPlayer}} warm their hands on your back, under your shirt, for 15 seconds, or drink 3.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Grinding, Lap & Movement ---
  { id: 457, text: "Dance behind {{randomOtherPlayer}} with your hands on their hips for one song, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 458, text: "Give {{randomOtherPlayer}} a 20-second lap dance with actual commitment, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 459, text: "Let {{randomOtherPlayer}} lead a slow grind for 15 seconds while you follow, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 460, text: "Sit on {{randomOtherPlayer}}'s lap and feed them their next sip, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 461, text: "Press your back to {{randomOtherPlayer}}'s chest and sway for a full song, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 462, text: "Straddle {{randomOtherPlayer}}'s knee and hold eye contact for 15 seconds, or drink 3.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Stripping ---
  { id: 463, text: "Let {{randomOtherPlayer}} remove one accessory from you using only their teeth, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 464, text: "Take off two layers in the sexiest way you can manage, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 465, text: "Peel off one layer while holding eye contact with {{randomOtherPlayer}}, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 466, text: "Trade shirts with {{randomOtherPlayer}} and wear theirs for the rest of the game, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 467, text: "Give {{randomOtherPlayer}} a lap dance and let them remove one item, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Spanking, Restraints & Power ---
  { id: 468, text: "Let {{randomOtherPlayer}} hold your wrists above your head for 15 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 469, text: "Give {{randomOtherPlayer}} one firm spank and let them return it, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 470, text: "Do whatever {{randomOtherPlayer}} tells you for the next full round, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 471, text: "Kneel in front of {{randomOtherPlayer}} and ask permission for your next move, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 472, text: "Let {{randomOtherPlayer}} blindfold you and trace one word on your skin to guess, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 473, text: "Hand {{randomOtherPlayer}} full control of your next two turns, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Simulated & Narrated ---
  { id: 474, text: "Narrate, step by step, how you'd spend an hour alone with {{randomOtherPlayer}}, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 475, text: "Whisper the filthiest thing you'd say in the moment to {{randomOtherPlayer}}, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 476, text: "Demonstrate the pace you prefer using only your hands on the table, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 477, text: "Give a 10-second preview of your best moves against {{randomOtherPlayer}}'s back, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 478, text: "Describe, in detail, exactly how you'd take {{randomOtherPlayer}} apart, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Phone & Reveal ---
  { id: 479, text: "Show {{randomOtherPlayer}} the spiciest thing in your phone; they decide if the group sees, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 480, text: "Text your last hookup one word that would get an immediate reply, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 481, text: "Reveal the wildest thing you've ever agreed to over text, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: More Group & Private Escalation ---
  { id: 482, text: "Pick two people to join you for a 15-second group slow dance, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 483, text: "Disappear with {{randomOtherPlayer}} for two minutes; the group guesses what happened, or you both finish your drinks.", nsfwLevel: 'Extreme' },
  { id: 484, text: "Everyone locks eyes with the person they'd most want right now; hold it for ten seconds or drink 2.", nsfwLevel: 'Extreme' },
  { id: 485, text: "Let the group pick two people to swap one dare; both must do it, or both finish your drinks.", nsfwLevel: 'Extreme' },
  { id: 486, text: "Kiss the two people beside you, then let them decide who kissed better, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 487, text: "Take {{randomOtherPlayer}} out of the room and come back with one item of clothing swapped, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: Final Escalation ---
  { id: 488, text: "Let {{randomOtherPlayer}} write one dare on your skin that you have to complete before your next turn, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 489, text: "Give {{randomOtherPlayer}} the most convincing preview of what a night with you looks like, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 490, text: "Let {{randomOtherPlayer}} choose: two layers gone or their dare, no questions asked.", nsfwLevel: 'Extreme' },
  { id: 491, text: "Close the round however you want with {{randomOtherPlayer}}, as long as it's bolder than your last turn, or finish your drink.", nsfwLevel: 'Extreme' },

  // --- Extreme: Drink If (Explicit Acts) ---
  { id: 492, text: "Drink if you've ever swallowed; if you never have, take 2 instead.", nsfwLevel: 'Extreme' },
  { id: 493, text: "Drink if you've ever let someone finish on your face.", nsfwLevel: 'Extreme' },
  { id: 494, text: "Drink if you've ever been double-penetrated.", nsfwLevel: 'Extreme' },
  { id: 495, text: "Drink if you've ever given or received a golden shower.", nsfwLevel: 'Extreme' },
  { id: 496, text: "Drink if you've ever been fisted, or done the fisting.", nsfwLevel: 'Extreme' },
  { id: 497, text: "Drink if you've ever had sex on your period.", nsfwLevel: 'Extreme' },
  { id: 498, text: "Drink if you've ever done anal without lube; respect.", nsfwLevel: 'Extreme' },
  { id: 499, text: "Drink if you've ever used a butt plug in the bedroom.", nsfwLevel: 'Extreme' },
  { id: 500, text: "Drink if you've ever been spit on in bed and liked it.", nsfwLevel: 'Extreme' },
  { id: 501, text: "Drink if you've ever squirted, or made someone else.", nsfwLevel: 'Extreme' },
  { id: 502, text: "Drink if you've ever had a hand around your throat and asked for more.", nsfwLevel: 'Extreme' },
  { id: 503, text: "Drink if you've ever finished more than once in a single session.", nsfwLevel: 'Extreme' },
  { id: 504, text: "Drink if you've ever deep-throated, dare or otherwise.", nsfwLevel: 'Extreme' },
  { id: 505, text: "Drink if you've ever tasted yourself.", nsfwLevel: 'Extreme' },
  { id: 506, text: "Drink if you've ever rimmed someone, or been rimmed.", nsfwLevel: 'Extreme' },
  { id: 507, text: "Drink if you've ever pegged someone, or been pegged.", nsfwLevel: 'Extreme' },
  { id: 508, text: "Drink if you've ever left nail marks down someone's back.", nsfwLevel: 'Extreme' },
  { id: 509, text: "Drink if you've ever come so hard you saw stars.", nsfwLevel: 'Extreme' },

  // --- Extreme: Drink If (Taboo & Wild) ---
  { id: 510, text: "Drink if you've ever had sex in a church, temple, or anywhere holy.", nsfwLevel: 'Extreme' },
  { id: 511, text: "Drink if you've ever hooked up at a funeral or a wedding.", nsfwLevel: 'Extreme' },
  { id: 512, text: "Drink if you've ever hooked up with a family member's friend.", nsfwLevel: 'Extreme' },
  { id: 513, text: "Drink if you've ever slept with someone 15+ years older or younger than you.", nsfwLevel: 'Extreme' },
  { id: 514, text: "Drink if you've ever slept with a friend's ex and never confessed.", nsfwLevel: 'Extreme' },
  { id: 515, text: "Drink if you've ever had sex at your workplace after hours.", nsfwLevel: 'Extreme' },
  { id: 516, text: "Drink if you've ever hooked up with someone twice your age.", nsfwLevel: 'Extreme' },
  { id: 517, text: "Drink if you've ever been the other person in an affair.", nsfwLevel: 'Extreme' },
  { id: 518, text: "Drink if you've ever hooked up with two people in the same night.", nsfwLevel: 'Extreme' },
  { id: 519, text: "Drink if you've ever hooked up with someone you wouldn't dare name out loud.", nsfwLevel: 'Extreme' },
  { id: 520, text: "Drink if you've ever had sex in your childhood bedroom as a grown adult.", nsfwLevel: 'Extreme' },

  // --- Extreme: Drink If (Paid & Provocative) ---
  { id: 521, text: "Drink if you've ever been paid for anything sexual; strip a layer if yes.", nsfwLevel: 'Extreme' },
  { id: 522, text: "Drink if you've ever had a sugar daddy or sugar mommy; lose a layer if it's still active.", nsfwLevel: 'Extreme' },
  { id: 523, text: "Drink if you've ever paid for sex; admit it or lose a layer.", nsfwLevel: 'Extreme' },
  { id: 524, text: "Drink if you've ever made money from a photo of yourself.", nsfwLevel: 'Extreme' },
  { id: 525, text: "Drink if you've ever had a spicy subscription account, or paid for someone else's.", nsfwLevel: 'Extreme' },

  // --- Extreme: Explicit Dares (Hands & Simulation) ---
  { id: 526, text: "Let {{randomOtherPlayer}} slip a hand into your waistband for 10 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 527, text: "Slide a hand under {{randomOtherPlayer}}'s clothes and tease for 15 seconds, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 528, text: "Let {{randomOtherPlayer}} undo your pants and slip a hand exactly where they like, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 529, text: "Suck {{randomOtherPlayer}}'s toe like you actually mean it, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 530, text: "Guide {{randomOtherPlayer}}'s hand exactly where you'd want it and hold it there for 10 seconds, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 531, text: "Let {{randomOtherPlayer}} decide where your hands go for the next 20 seconds, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 532, text: "Simulate going down on {{randomOtherPlayer}} for 10 seconds, fully clothed, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 533, text: "Let {{randomOtherPlayer}} grind against your thigh until the song changes, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 534, text: "Whisper to {{randomOtherPlayer}} exactly how you'd finish them off, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 535, text: "Put two fingers in {{randomOtherPlayer}}'s mouth and let them show you what they'd do, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 536, text: "Kiss and bite your way down {{randomOtherPlayer}}'s stomach to their waistband, or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 537, text: "Press against {{randomOtherPlayer}} from behind and set the pace for 15 seconds, or drink 3.", nsfwLevel: 'Extreme' },
  { id: 538, text: "Let {{randomOtherPlayer}} slide your underwear off using only their teeth, or take 3 drinks.", nsfwLevel: 'Extreme' }
];
