
export type NsfwLevel = 'Mild' | 'Medium' | 'Extreme';

export type Prompt = {
  id: number;
  text: string;
  nsfwLevel: NsfwLevel;
};

export const PROMPTS: Prompt[] = [
  // Mild
  { id: 1, text: "Share your most embarrassing childhood nickname and the story behind it.", nsfwLevel: 'Mild' },
  { id: 2, text: "What's your go-to karaoke song, even if you can't sing?", nsfwLevel: 'Mild' },
  { id: 3, text: "If you could have any superpower, what would it be and why?", nsfwLevel: 'Mild' },
  { id: 4, text: "Describe your dream vacation in detail.", nsfwLevel: 'Mild' },
  { id: 5, text: "What's a weird food combination you secretly enjoy?", nsfwLevel: 'Mild' },

  // Medium
  { id: 6, text: "Describe the most awkward first date you've ever been on.", nsfwLevel: 'Medium' },
  { id: 7, text: "What's a white lie you've told that spiraled out of control?", nsfwLevel: 'Medium' },
  { id: 8, text: "If you had to choose, would you rather give up cheese or oral sex for a year?", nsfwLevel: 'Medium' },
  { id: 9, text: "What's the most trouble you got into as a teenager?", nsfwLevel: 'Medium' },
  { id: 10, text: "Share a secret you've never told anyone in this room.", nsfwLevel: 'Medium' },

  // Extreme
  { id: 11, text: "What's the kinkiest thing you've ever considered trying?", nsfwLevel: 'Extreme' },
  { id: 12, text: "Describe your most scandalous public display of affection.", nsfwLevel: 'Extreme' },
  { id: 13, text: "Who in this room would you most likely have a one-night stand with, and why?", nsfwLevel: 'Extreme' },
  { id: 14, text: "What's the riskiest place you've ever had sex?", nsfwLevel: 'Extreme' },
  { id: 15, text: "Share your raunchiest, most NSFW fantasy in detail.", nsfwLevel: 'Extreme' },
  { id: 16, text: "Truth: Have you ever sent a nude to the wrong person? Dare: Send a flirty text to your latest contact.", nsfwLevel: 'Extreme' },
  { id: 17, text: "What's the most embarrassing thing on your phone right now?", nsfwLevel: 'Extreme' },
  { id: 18, text: "Lick {{randomOtherPlayer}}’s nipples for 10 seconds.", nsfwLevel: 'Extreme' },
  { id: 19, text: "If you’ve had a threesome, take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 20, text: "Remove one piece of clothing for each person here you’ve kissed.", nsfwLevel: 'Extreme' },
  { id: 21, text: "Pour a shot into {{randomOtherPlayer}}’s belly button and drink it.", nsfwLevel: 'Extreme' },
  { id: 22, text: "Give {{randomOtherPlayer}} a hickey for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 23, text: "Spank {{randomOtherPlayer}} — hard.", nsfwLevel: 'Extreme' },
  { id: 24, text: "Reveal your dirtiest sexual fantasy or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 25, text: "Blindfold {{randomOtherPlayer}} and kiss them somewhere unexpected.", nsfwLevel: 'Extreme' },
  { id: 26, text: "Sit on {{randomOtherPlayer}}’s lap for the next 5 rounds.", nsfwLevel: 'Extreme' },
  { id: 27, text: "Remove {{randomOtherPlayer}}’s top.", nsfwLevel: 'Extreme' },
  { id: 28, text: "If you’ve ever filmed yourself having sex, take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 29, text: "Swap underwear with {{randomOtherPlayer}} for the next 10 minutes.", nsfwLevel: 'Extreme' },
  { id: 30, text: "Suck on {{randomOtherPlayer}}’s finger slowly.", nsfwLevel: 'Extreme' },
  { id: 31, text: "Take a body shot off {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 32, text: "Whisper the last dirty text you sent into {{randomOtherPlayer}}’s ear.", nsfwLevel: 'Extreme' },
  { id: 33, text: "Pick {{randomOtherPlayer}} to give you a lap dance.", nsfwLevel: 'Extreme' },
  { id: 34, text: "Strip down to your underwear for the next 3 rounds.", nsfwLevel: 'Extreme' },
  { id: 35, text: "If you’ve had sex outdoors, take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 36, text: "Flash the group or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 37, text: "Make out with {{randomOtherPlayer}} for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 38, text: "Share your most recent sex dream or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 39, text: "Put ice down your underwear for the next round.", nsfwLevel: 'Extreme' },
  { id: 40, text: "Lick whipped cream off {{randomOtherPlayer}}’s neck.", nsfwLevel: 'Extreme' },
  { id: 41, text: "Tell the group how many people you’ve slept with.", nsfwLevel: 'Extreme' },
  { id: 42, text: "If you've ever joined the mile high club, take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 43, text: "Remove {{randomOtherPlayer}}’s pants using only your teeth.", nsfwLevel: 'Extreme' },
  { id: 44, text: "Suck on {{randomOtherPlayer}}’s toe or take 2 shots.", nsfwLevel: 'Extreme' },
  { id: 45, text: "Call your last hookup and say “I miss your body” or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 46, text: "Show the group the last nude you received (or take 5 drinks).", nsfwLevel: 'Extreme' },
  { id: 47, text: "Massage {{randomOtherPlayer}}’s inner thighs for 30 seconds.", nsfwLevel: 'Extreme' },
  { id: 48, text: "Get handcuffed to a chair for the next 5 rounds.", nsfwLevel: 'Extreme' },
  { id: 49, text: "Take a naked selfie (not shared) or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 50, text: "Put an ice cube in your mouth and kiss {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 51, text: "Strip completely naked for the next round or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 52, text: "Get blindfolded and allow {{randomOtherPlayer}} to touch you wherever they want for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 53, text: "Give {{randomOtherPlayer}} a strip tease for one full song.", nsfwLevel: 'Extreme' },
  { id: 54, text: "French kiss {{randomOtherPlayer}} while the group watches.", nsfwLevel: 'Extreme' },
  { id: 55, text: "Tell the group your biggest sexual secret or take 4 shots.", nsfwLevel: 'Extreme' },
  { id: 56, text: "If you’ve had a one-night stand this year, remove one item of clothing.", nsfwLevel: 'Extreme' },
  { id: 57, text: "Kiss everyone in the room on the lips.", nsfwLevel: 'Extreme' },
  { id: 58, text: "Let {{randomOtherPlayer}} draw something on your chest — clothing off.", nsfwLevel: 'Extreme' },
  { id: 59, text: "Demonstrate your favorite sex position (fully clothed) or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 60, text: "If you’ve ever slept with {{randomOtherPlayer}}, say who or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 61, text: "Lick {{randomOtherPlayer}}’s inner thigh.", nsfwLevel: 'Extreme' },
  { id: 62, text: "Wear nothing but your underwear for the rest of the game.", nsfwLevel: 'Extreme' },
  { id: 63, text: "Swap a piece of clothing with {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 64, text: "Describe the kinkiest thing you’ve done, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 65, text: "Get spanked with a belt by {{randomOtherPlayer}} or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 66, text: "Perform a fake orgasm for 10 seconds.", nsfwLevel: 'Extreme' },
  { id: 67, text: "Let {{randomOtherPlayer}} tie you up with whatever’s in the room.", nsfwLevel: 'Extreme' },
  { id: 68, text: "Start with a teasing kiss to {{randomOtherPlayer}} — just a peck — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 69, text: "Full makeout session with {{randomOtherPlayer}} — or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 70, text: "Strip down completely — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 71, text: "Kiss any spot {{randomOtherPlayer}} chooses — or take 2 shots.", nsfwLevel: 'Extreme' },
  { id: 72, text: "Pick any body part on {{randomOtherPlayer}} and plant a long, wet kiss — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 73, text: "Leave a visible hickey on {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 74, text: "Take a shot while making eye contact with {{randomOtherPlayer}} — if you break eye contact, take another.", nsfwLevel: 'Extreme' },
  { id: 75, text: "Take a body shot off {{randomOtherPlayer}} — or take 2 shots yourself.", nsfwLevel: 'Extreme' },
  { id: 76, text: "Lick whipped cream off any body part {{randomOtherPlayer}} chooses — or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 77, text: "Cover any body part you choose on {{randomOtherPlayer}} with whipped cream and lick it clean — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 78, text: "Bonus round — spin again, but everyone takes a drink.", nsfwLevel: 'Extreme' },
  { id: 79, text: "Use only your mouth to melt ice on {{randomOtherPlayer}}’s body — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 80, text: "Let {{randomOtherPlayer}} melt ice on your body using only their mouth — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 81, text: "Give {{randomOtherPlayer}} a full lap dance — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 82, text: "Receive a lap dance from {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 83, text: "Motorboat {{randomOtherPlayer}} — or take 2 shots.", nsfwLevel: 'Extreme' },
  { id: 84, text: "Whisper your dirtiest fantasy into {{randomOtherPlayer}}’s ear — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 85, text: "Explore {{randomOtherPlayer}}'s body with your hands for 30 seconds — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 86, text: "Let {{randomOtherPlayer}} do whatever they want to you for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 87, text: "Do anything you want to {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 88, text: "Blindfold {{randomOtherPlayer}} and draw again — everyone else takes a drink.", nsfwLevel: 'Extreme' },
  { id: 89, text: "Blindfold yourself and let {{randomOtherPlayer}} control you — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 90, text: "Tease {{randomOtherPlayer}}'s nipples with ice — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 91, text: "Lucky round — nothing happens. Everyone cheers and drinks.", nsfwLevel: 'Extreme' },
  { id: 92, text: "Kiss a trail down {{randomOtherPlayer}}’s stomach — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 93, text: "Kiss {{randomOtherPlayer}}'s inner thighs — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 94, text: "Simulate 69 position with {{randomOtherPlayer}} for 30 seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 95, text: "Kiss down the length of {{randomOtherPlayer}}’s spine — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 96, text: "Use a toy of {{randomOtherPlayer}}'s choice on yourself for 30 seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 97, text: "Use a toy of your choice on {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 98, text: "Tie {{randomOtherPlayer}} up completely — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 99, text: "Get tied up by {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 100, text: "Give {{randomOtherPlayer}} a sensual massage above the waist for 1 minute — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 101, text: "Give {{randomOtherPlayer}} a deep massage below the waist for 1 minute — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 102, text: "Remove any piece of clothing — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 103, text: "Let {{randomOtherPlayer}} remove any piece of your clothing — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 104, text: "Hover your lips close to {{randomOtherPlayer}}'s without kissing for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 105, text: "Use only your teeth to remove one piece of {{randomOtherPlayer}}’s clothing — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 106, text: "Let {{randomOtherPlayer}} whisper their dirtiest thought into your ear — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 107, text: "Grind on {{randomOtherPlayer}} for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 108, text: "Let {{randomOtherPlayer}} grind on you for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 109, text: "Reveal your wildest sexual fantasy — or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 110, text: "Slowly trace your fingertips across {{randomOtherPlayer}}'s bare ass — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 111, text: "Run your lips gently over any body part of {{randomOtherPlayer}} above the waist — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 112, text: "Run your lips gently over any body part of {{randomOtherPlayer}} below the waist — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 113, text: "Knock {{randomOtherPlayer}} over and “accidentally” get busy for a few seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 114, text: "Tie {{randomOtherPlayer}} up and tease for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 115, text: "Get tied up by {{randomOtherPlayer}} and teased for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 116, text: "Pinch {{randomOtherPlayer}}'s nipples — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 117, text: "Let {{randomOtherPlayer}} pinch your nipples — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 118, text: "Spank {{randomOtherPlayer}} hard for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 119, text: "Get spanked hard by {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 120, text: "Put on a sexy song and strip one article of clothing — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 121, text: "Put on a sexy song and let {{randomOtherPlayer}} remove one article of your clothing — or take 4 drinks.", nsfwLevel: 'Extreme' },
];

