export type NsfwLevel = 'Mild' | 'Medium' | 'Extreme';

export type Prompt = {
  id: number;
  text: string;
  nsfwLevel: NsfwLevel;
};

export const PROMPTS: Prompt[] = [
  // ============================================================================
  // MILD (IDs 1-10) - Icebreakers & Getting to Know You
  // ============================================================================
  
  // --- Mild: Icebreakers ---
  { id: 1, text: "Share your most embarrassing childhood nickname and the story behind it.", nsfwLevel: 'Mild' },
  { id: 2, text: "What's your go-to karaoke song, even if you can't sing?", nsfwLevel: 'Mild' },
  { id: 3, text: "If you could have any superpower, what would it be and why?", nsfwLevel: 'Mild' },
  { id: 4, text: "Describe your dream vacation in detail.", nsfwLevel: 'Mild' },
  { id: 5, text: "What's a weird food combination you secretly enjoy?", nsfwLevel: 'Mild' },

  // ============================================================================
  // MEDIUM (IDs 100-299) - Flirty Questions, Confessions & Light Dares
  // ============================================================================

  // --- Medium: Confessions & Stories ---
  { id: 100, text: "Describe the most awkward first date you've ever been on.", nsfwLevel: 'Medium' },
  { id: 101, text: "What's a white lie you've told that spiraled out of control?", nsfwLevel: 'Medium' },
  { id: 102, text: "What's the most trouble you got into as a teenager?", nsfwLevel: 'Medium' },
  { id: 103, text: "Share a secret you've never told anyone in this room.", nsfwLevel: 'Medium' },
  { id: 104, text: "What's one thing you've done that you'd never tell your parents?", nsfwLevel: 'Medium' },
  { id: 105, text: "What's the craziest place you've ever had sex?", nsfwLevel: 'Medium' },
  { id: 106, text: "Share the dirtiest DM you've ever sent or received.", nsfwLevel: 'Medium' },
  { id: 107, text: "Have you ever cheated? Be honest or drink 3 times.", nsfwLevel: 'Medium' },
  { id: 108, text: "What's the most romantic thing someone's done for you?", nsfwLevel: 'Medium' },
  { id: 109, text: "If you've ever stood someone up on a date drink 8 times.", nsfwLevel: 'Medium' },
  { id: 110, text: "Have you ever used a cheesy pickup line? Say it now.", nsfwLevel: 'Medium' },
  { id: 111, text: "If you've ever used a pickup line online or in real life, drink 4 times and tell the group.", nsfwLevel: 'Medium' },
  { id: 112, text: "Admit what the worst porn you've watched to give out 5 drinks.", nsfwLevel: 'Medium' },
  { id: 113, text: "Come up with a name for an erotic fiction book and detail what it's about.", nsfwLevel: 'Medium' },

  // --- Medium: Flirty Questions ---
  { id: 114, text: "What's your favorite body part on {{randomOtherPlayer}}?", nsfwLevel: 'Medium' },
  { id: 115, text: "What part of your body do you love being touched?", nsfwLevel: 'Medium' },
  { id: 116, text: "If you had to be stuck in an elevator with one person here — who?", nsfwLevel: 'Medium' },
  { id: 117, text: "What's your biggest turn-on that isn't sexual?", nsfwLevel: 'Medium' },
  { id: 118, text: "When did you first realize you were hot?", nsfwLevel: 'Medium' },
  { id: 119, text: "What's your favorite compliment to receive?", nsfwLevel: 'Medium' },
  { id: 120, text: "If someone in this room kissed you right now, who'd you want it to be?", nsfwLevel: 'Medium' },
  { id: 121, text: "What's the longest dry spell you've ever had?", nsfwLevel: 'Medium' },
  { id: 122, text: "If you had to choose, would you rather give up cheese or oral sex for a year?", nsfwLevel: 'Medium' },
  { id: 123, text: "Dominant or submissive? Those that are dominant give out 4 drinks, while those that are submissive can drink 2.", nsfwLevel: 'Medium' },
  { id: 124, text: "How many people do you wish you'd had sex with in your life? Each player drinks that number.", nsfwLevel: 'Medium' },
  { id: 125, text: "Point at a player that you would want to have sex with and make them drink 6 times.", nsfwLevel: 'Medium' },

  // --- Medium: Drink If (Sexual History) ---
  { id: 126, text: "Drink if you have ever fantasized about someone in this room.", nsfwLevel: 'Medium' },
  { id: 127, text: "Take a drink for each person you've kissed in this room.", nsfwLevel: 'Medium' },
  { id: 128, text: "Take a sip every time you've sexted in the past week.", nsfwLevel: 'Medium' },
  { id: 129, text: "Drink if you've ever skinny-dipped.", nsfwLevel: 'Medium' },
  { id: 130, text: "Drink if you've ever sent a nude to the wrong person.", nsfwLevel: 'Medium' },
  { id: 131, text: "Drink if you've ever hooked up with a coworker.", nsfwLevel: 'Medium' },
  { id: 132, text: "Drink if you've ever faked an orgasm.", nsfwLevel: 'Medium' },
  { id: 133, text: "Finish your drink if you've ever faked an orgasm and the other person called you out on it.", nsfwLevel: 'Medium' },
  { id: 134, text: "Drink if you've ever texted 'you up?' past midnight.", nsfwLevel: 'Medium' },
  { id: 135, text: "Take 1 drink for every sex toy you own.", nsfwLevel: 'Medium' },
  { id: 136, text: "If you've ever moaned someone else's name by accident — drink twice.", nsfwLevel: 'Medium' },
  { id: 137, text: "If you've ever hooked up with someone from a dating app, take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 138, text: "Drink if you've ever lied about your body count.", nsfwLevel: 'Medium' },
  { id: 139, text: "Drink if you've ever had a crush on a teacher.", nsfwLevel: 'Medium' },
  { id: 140, text: "Drink if you've flirted to get something for free.", nsfwLevel: 'Medium' },
  { id: 141, text: "If you have ever done anal drink 6 times.", nsfwLevel: 'Medium' },
  { id: 142, text: "Anyone who masturbated today drink 4 times.", nsfwLevel: 'Medium' },
  { id: 143, text: "Anyone that has been skinny dipping drink 4 times.", nsfwLevel: 'Medium' },
  { id: 144, text: "If you've ever sucked your partner's toes drink 4 times.", nsfwLevel: 'Medium' },
  { id: 145, text: "If you've had sex 3 or more times in one night drink 6 times.", nsfwLevel: 'Medium' },
  { id: 146, text: "If you've ever faked an orgasm drink 4 times.", nsfwLevel: 'Medium' },
  { id: 147, text: "Drink 8 times if you've seen another one of the players naked.", nsfwLevel: 'Medium' },
  { id: 148, text: "If you've ever had sex in a car drink 5 times.", nsfwLevel: 'Medium' },
  { id: 149, text: "If you've ever used handcuffs or rope in bed give out 7 drinks.", nsfwLevel: 'Medium' },
  { id: 150, text: "If your body count is over 20 drink 4 times.", nsfwLevel: 'Medium' },
  { id: 151, text: "If you've had sex with more than one person in one night drink 8 times.", nsfwLevel: 'Medium' },
  { id: 152, text: "If you've ever participated in an orgy drink 4 times.", nsfwLevel: 'Medium' },
  { id: 153, text: "If you've ever given oral sex, give out 6 drinks for being so generous.", nsfwLevel: 'Medium' },
  { id: 154, text: "Anyone who has filmed a porn film drink 4 times.", nsfwLevel: 'Medium' },
  { id: 155, text: "If you've taken someone's virginity drink 3 times.", nsfwLevel: 'Medium' },
  { id: 156, text: "If you've ever had sex in a hot tub or pool drink 5 times.", nsfwLevel: 'Medium' },
  { id: 157, text: "If you've ever been streaking drink 5 times.", nsfwLevel: 'Medium' },
  { id: 158, text: "If you've ever had sex with a person you only met within 24 hours drink 4 times.", nsfwLevel: 'Medium' },
  { id: 159, text: "If you have ever had sex in public drink 5 times.", nsfwLevel: 'Medium' },
  { id: 160, text: "Have you ever done 69 before? Drink 4 if yes.", nsfwLevel: 'Medium' },
  { id: 161, text: "Anyone that has had sex outdoors can drink 4 times.", nsfwLevel: 'Medium' },
  { id: 162, text: "If you've ever given or received a hickey drink 4.", nsfwLevel: 'Medium' },
  { id: 163, text: "If you've ever masturbated while in a public place drink 3 times.", nsfwLevel: 'Medium' },

  // --- Medium: Drink If (Risqué Sexual) ---
  { id: 246, text: "Drink if you've ever had sex on the first date.", nsfwLevel: 'Medium' },
  { id: 247, text: "Drink if you've ever hooked up with someone twice your age (or half your age).", nsfwLevel: 'Medium' },
  { id: 248, text: "Drink if you've ever had a friends-with-benefits situation that got messy.", nsfwLevel: 'Medium' },
  { id: 249, text: "Drink if you've ever slept with someone whose name you didn't know.", nsfwLevel: 'Medium' },
  { id: 250, text: "Drink if you've ever had sex while someone else was in the room.", nsfwLevel: 'Medium' },
  { id: 251, text: "Drink if you've ever woken up and regretted who was next to you.", nsfwLevel: 'Medium' },
  { id: 252, text: "Drink if you've ever had a one-night stand and snuck out before they woke up.", nsfwLevel: 'Medium' },
  { id: 253, text: "Drink if you've ever hooked up with two people in the same friend group.", nsfwLevel: 'Medium' },
  { id: 254, text: "Drink if you've ever had sex somewhere you could have been arrested.", nsfwLevel: 'Medium' },
  { id: 255, text: "Drink if you've ever been caught having sex.", nsfwLevel: 'Medium' },
  { id: 256, text: "Drink if you have nudes of someone in this room saved on your phone.", nsfwLevel: 'Medium' },
  { id: 257, text: "Drink if you've ever screenshot someone's nudes to send to a friend.", nsfwLevel: 'Medium' },
  { id: 258, text: "Drink if you've ever had sex while at work.", nsfwLevel: 'Medium' },
  { id: 259, text: "Drink if you've ever sent a nude to multiple people.", nsfwLevel: 'Medium' },
  { id: 260, text: "Drink if you've ever had facetime sex.", nsfwLevel: 'Medium' },
  { id: 261, text: "Drink if you've ever watched porn with a partner.", nsfwLevel: 'Medium' },
  { id: 262, text: "Drink if you've ever tried roleplay in the bedroom.", nsfwLevel: 'Medium' },
  { id: 263, text: "Drink if you've ever been choked during sex (and liked it).", nsfwLevel: 'Medium' },
  { id: 264, text: "Drink if you've ever called someone 'daddy' or 'mommy' in bed.", nsfwLevel: 'Medium' },
  { id: 265, text: "Drink if you've ever used a sex toy with a partner.", nsfwLevel: 'Medium' },
  { id: 266, text: "Drink if you've ever been tied up or tied someone else up.", nsfwLevel: 'Medium' },
  { id: 267, text: "Drink if you've ever hooked up with an ex.", nsfwLevel: 'Medium' },
  { id: 268, text: "Drink if you've ever hooked up with someone who was in a relationship.", nsfwLevel: 'Medium' },
  { id: 269, text: "Drink if you've ever hooked up with a friend's significant other.", nsfwLevel: 'Medium' },
  { id: 270, text: "Drink if you've ever lied about your body count to someone you were dating.", nsfwLevel: 'Medium' },

  // --- Medium: Drink If (Random/Fun) ---
  { id: 164, text: "Anyone with a tattoo drinks 4 times.", nsfwLevel: 'Medium' },
  { id: 165, text: "If you've ever been arrested drink once.", nsfwLevel: 'Medium' },
  { id: 166, text: "If you've ever been in a car accident, drink 4 times.", nsfwLevel: 'Medium' },
  { id: 167, text: "Anyone that has vomited in public drinks 3 times.", nsfwLevel: 'Medium' },
  { id: 168, text: "Everyone wearing glasses (or contacts) right now drink 3 times.", nsfwLevel: 'Medium' },
  { id: 169, text: "If you've had the police called on you drink 4 times.", nsfwLevel: 'Medium' },
  { id: 170, text: "Anyone that has done drugs tonight, drink twice.", nsfwLevel: 'Medium' },
  { id: 171, text: "If you're wearing some whacky socks give out 2 drinks.", nsfwLevel: 'Medium' },
  { id: 172, text: "Anyone whose name starts with 'J' can choose someone to finish half their drink.", nsfwLevel: 'Medium' },
  { id: 173, text: "Anyone holding a drink has to drink twice.", nsfwLevel: 'Medium' },
  { id: 174, text: "Everyone that doesn't wear glasses drinks 3 times.", nsfwLevel: 'Medium' },

  // --- Medium: Voting & Group Decisions ---
  { id: 175, text: "{{randomOtherPlayer}}, Give a drink to who you think has the best lips in the group.", nsfwLevel: 'Medium' },
  { id: 176, text: "Pick which player is most likely to give the best head, the winner gets to give out 4 drinks.", nsfwLevel: 'Medium' },
  { id: 177, text: "Who here is most likely to be a freak in the sheets? They drink 3 times.", nsfwLevel: 'Medium' },
  { id: 178, text: "Who would you most want to receive a lap dance from? That person gives out 5 drinks.", nsfwLevel: 'Medium' },
  { id: 179, text: "Who here is most likely to have a secret OnlyFans? They drink 4 times.", nsfwLevel: 'Medium' },
  { id: 180, text: "{{randomOtherPlayer}}, who do you think is the be the best kisser in this room? They have to prove it on someone of their choice.", nsfwLevel: 'Medium' },
  { id: 181, text: "Pick who is most likely to send the best sexts. They have to show their most recent sext or drink 4 times.", nsfwLevel: 'Medium' },
  { id: 182, text: "Who has the best ass in the room? Everyone has to slap it once or drink twice.", nsfwLevel: 'Medium' },
  { id: 183, text: "{{randomOtherPlayer}}, who do you think is secretly the kinkiest? They have to confirm or deny.", nsfwLevel: 'Medium' },
  { id: 184, text: "Pick who is the least drunk and they will finish their drink.", nsfwLevel: 'Medium' },
  { id: 185, text: "Everyone vote for a player to down half their drink.", nsfwLevel: 'Medium' },
  { id: 186, text: "The person with the smallest boobs must drink.", nsfwLevel: 'Medium' },
  { id: 187, text: "The person with the biggest boobs must allow everyone to feel them.", nsfwLevel: 'Medium' },
  { id: 188, text: "{{randomOtherPlayer}}, who has the most 'innocent face but dirty mind' energy? They drink 4.", nsfwLevel: 'Medium' },
  { id: 189, text: "{{randomOtherPlayer}}, choose whose nude you would most like to see. They can either do it or drink 4 times.", nsfwLevel: 'Medium' },
  { id: 190, text: "{{randomOtherPlayer}}, Pick someone else to drink with you.", nsfwLevel: 'Medium' },

  // --- Medium: Dares & Physical (Light) ---
  { id: 191, text: "Give {{randomOtherPlayer}} a quick peck on the lips — or take 1 drink.", nsfwLevel: 'Medium' },
  { id: 192, text: "Let {{randomOtherPlayer}} kiss you anywhere above the shoulders — or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 193, text: "Kiss {{randomOtherPlayer}} anywhere you choose above the waist — or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 194, text: "Let {{randomOtherPlayer}} run their hands through your hair for 15 seconds — or take 1 drink.", nsfwLevel: 'Medium' },
  { id: 195, text: "Hold {{randomOtherPlayer}}'s face in your hands and stare into their eyes for 30 seconds — first to laugh drinks.", nsfwLevel: 'Medium' },
  { id: 196, text: "Trace your finger slowly from {{randomOtherPlayer}}'s wrist to their shoulder — or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 197, text: "Let {{randomOtherPlayer}} whisper something dirty in your ear — you have to keep a straight face or drink.", nsfwLevel: 'Medium' },
  { id: 198, text: "Whisper your biggest turn-on into {{randomOtherPlayer}}'s ear — or take 2 drinks.", nsfwLevel: 'Medium' },
  { id: 199, text: "Get blindfolded and guess who kisses you — if wrong, drink.", nsfwLevel: 'Medium' },
  { id: 200, text: "Lick {{randomOtherPlayer}}'s neck — no hands.", nsfwLevel: 'Medium' },
  { id: 201, text: "Give {{randomOtherPlayer}} a massage with both hands — no speaking.", nsfwLevel: 'Medium' },
  { id: 202, text: "Make intense eye contact with {{randomOtherPlayer}} while slowly taking a sip of their drink.", nsfwLevel: 'Medium' },
  { id: 203, text: "Stare into {{randomOtherPlayer}}'s eyes without breaking eye contact for 60 seconds.", nsfwLevel: 'Medium' },
  { id: 204, text: "Perform their best attempt at a romantic movie scene with {{randomOtherPlayer}}.", nsfwLevel: 'Medium' },
  { id: 205, text: "Slow dance with {{randomOtherPlayer}} to the next song, regardless of what comes on.", nsfwLevel: 'Medium' },
  { id: 206, text: "Do a sexual dance in front of the group, or finish your drink.", nsfwLevel: 'Medium' },
  { id: 207, text: "Make an orgasm face until another player makes eye contact with you.", nsfwLevel: 'Medium' },
  { id: 208, text: "Give a lap dance to {{randomOtherPlayer}}.", nsfwLevel: 'Medium' },
  { id: 209, text: "Sit on {{randomOtherPlayer}}'s lap for the next two rounds.", nsfwLevel: 'Medium' },
  { id: 210, text: "Remove one article of your own clothing — or take 3 drinks.", nsfwLevel: 'Medium' },
  { id: 211, text: "Let {{randomOtherPlayer}} choose which article of clothing you remove — or take 4 drinks.", nsfwLevel: 'Medium' },
  { id: 212, text: "Anyone willing to take their pants off can give out 10 drinks.", nsfwLevel: 'Medium' },
  { id: 213, text: "Anyone willing to take their top off can give out 8 drinks.", nsfwLevel: 'Medium' },
  { id: 214, text: "Anyone with buttons on their shirt must unbutton all of them and drink 2 times for each.", nsfwLevel: 'Medium' },
  { id: 215, text: "Anyone with their nipples out right now can give out 6 drinks.", nsfwLevel: 'Medium' },

  // --- Medium: Truth or Dare Mechanics ---
  { id: 216, text: "Ask {{randomOtherPlayer}} 'truth or dare?' — you pick their outcome.", nsfwLevel: 'Medium' },
  { id: 217, text: "Let {{randomOtherPlayer}} come up with a dare for you — no backing out.", nsfwLevel: 'Medium' },
  { id: 218, text: "Go around the room and take a turn each to ask another player any question, 10 drinks in case of refusal.", nsfwLevel: 'Medium' },

  // --- Medium: Reveals & Confessions (Incentivized) ---
  { id: 219, text: "Anyone willing to reveal their weirdest sexual kink can give out 6 drinks.", nsfwLevel: 'Medium' },
  { id: 220, text: "Anyone willing to say the weirdest place they've had sex can give out 7 drinks.", nsfwLevel: 'Medium' },
  { id: 221, text: "The player to most recently shave their pubic area gives out 6 drinks.", nsfwLevel: 'Medium' },
  { id: 222, text: "The person who most recently measured their penis gives out 5 drinks.", nsfwLevel: 'Medium' },
  { id: 223, text: "Any player willing to admit the weirdest thing they've masturbated to gives out 6 drinks.", nsfwLevel: 'Medium' },
  { id: 224, text: "Any player willing to show a nude to the group gives out 10 drinks.", nsfwLevel: 'Medium' },
  { id: 225, text: "Say your body count to give out 12 drinks, if not, drink 2.", nsfwLevel: 'Medium' },
  { id: 226, text: "Gives the group free access to their phone for 2 minutes and can give out 10 drinks.", nsfwLevel: 'Medium' },
  { id: 227, text: "{{randomOtherPlayer}} and you have to admit what you like to be called in bed to give out 5 drinks.", nsfwLevel: 'Medium' },
  { id: 228, text: "{{randomOtherPlayer}} and you share your weirdest sexual fantasy and give out 5 drinks.", nsfwLevel: 'Medium' },
  { id: 229, text: "{{randomOtherPlayer}} and you reveal your weirdest turn on. Everyone votes for the weirdest one, who can give out 8 drinks.", nsfwLevel: 'Medium' },

  // --- Medium: Compliments & Flirting ---
  { id: 230, text: "Compliment {{randomOtherPlayer}} for 15 seconds without stopping.", nsfwLevel: 'Medium' },
  { id: 231, text: "{{randomOtherPlayer}} and you give a personalized compliment to everyone in the room or drink 7 times.", nsfwLevel: 'Medium' },

  // --- Medium: Games & Challenges ---
  { id: 232, text: "Play 'Thumb War' with {{randomOtherPlayer}} — loser drinks twice.", nsfwLevel: 'Medium' },
  { id: 233, text: "Act out another player, first person to guess it gives out 8 drinks.", nsfwLevel: 'Medium' },
  { id: 234, text: "The most chatty person has to stop talking for 2 minutes and give out 9 drinks.", nsfwLevel: 'Medium' },
  { id: 235, text: "{{randomOtherPlayer}} can give out a drink every time you have to drink.", nsfwLevel: 'Medium' },
  { id: 236, text: "Everyone vote for the person that can do the most pushups, they can give out 2 drinks for every 5 pushups that they do.", nsfwLevel: 'Medium' },

  // --- Medium: Simple Drinking Commands ---
  { id: 237, text: "Everyone take a sip of your drink.", nsfwLevel: 'Medium' },
  { id: 238, text: "Youngest person in the room drinks 3 times.", nsfwLevel: 'Medium' },
  { id: 239, text: "Down your drink.", nsfwLevel: 'Medium' },
  { id: 240, text: "Women finish your drink.", nsfwLevel: 'Medium' },
  { id: 241, text: "Men drink 5 times.", nsfwLevel: 'Medium' },
  { id: 242, text: "Men finish your drink.", nsfwLevel: 'Medium' },
  { id: 243, text: "Anyone that has had an STI drinks 5 times.", nsfwLevel: 'Medium' },
  { id: 244, text: "Anyone whose partner is older than them gives out 3 drinks.", nsfwLevel: 'Medium' },
  { id: 245, text: "Drink as many times as people you've slept with.", nsfwLevel: 'Medium' },
  { id: 246, text: "Anyone born in the summer, drink", nsfwLevel: 'Medium' },
  { id: 247, text: "Anyone born in the spring, drink", nsfwLevel: 'Medium' },
  { id: 248, text: "Anyone born in the winter, drink", nsfwLevel: 'Medium' },
  { id: 249, text: "Anyone born in the Fall, drink", nsfwLevel: 'Medium' },
  { id: 250, text: "Anyone who has looked at an ex's instagram profile this week, drink", nsfwLevel: 'Medium' },
  { id: 251, text: "Anyone who has lied about their age to sleep with someone, drink", nsfwLevel: 'Medium' },
  { id: 252, text: "Anyone who has been cheated on, the group drinks for you", nsfwLevel: 'Medium' },
  { id: 253, text: "Anyone wearing black, drinks 3 times", nsfwLevel: 'Medium' },
  { id: 254, text: "Anyone wearing white, drinks 2 times", nsfwLevel: 'Medium' },
  { id: 255, text: "Anyone with a piercing (other than ears), drinks 3 times", nsfwLevel: 'Medium' },
  { id: 256, text: "Anyone not wearing socks rights now, take a drink", nsfwLevel: 'Medium' },
  { id: 257, text: "Anyone not wearing underwear, take a drink", nsfwLevel: 'Medium' },
  { id: 258, text: "Anyone showing cleavage right now, take a drink", nsfwLevel: 'Medium' },
  { id: 259, text: "Shortest person in the room, finish your drink", nsfwLevel: 'Medium' },

  // ============================================================================
  // EXTREME (IDs 300-499) - Physical Dares, Explicit Content & Wild Cards
  // ============================================================================

  // --- Extreme: Confessions & Questions ---
  { id: 300, text: "What's the kinkiest thing you've ever considered trying?", nsfwLevel: 'Extreme' },
  { id: 301, text: "Describe your most scandalous public display of affection.", nsfwLevel: 'Extreme' },
  { id: 302, text: "Who in this room would you most likely have a one-night stand with, and why?", nsfwLevel: 'Extreme' },
  { id: 303, text: "What's the riskiest place you've ever had sex?", nsfwLevel: 'Extreme' },
  { id: 304, text: "Share your raunchiest, most NSFW fantasy in detail.", nsfwLevel: 'Extreme' },
  { id: 305, text: "Truth: Have you ever sent a nude to the wrong person? Dare: Send a flirty text to your latest contact.", nsfwLevel: 'Extreme' },
  { id: 306, text: "What's the most embarrassing thing on your phone right now?", nsfwLevel: 'Extreme' },
  { id: 307, text: "Reveal your dirtiest sexual fantasy or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 308, text: "Share your most recent sex dream or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 309, text: "Tell the group how many people you've slept with.", nsfwLevel: 'Extreme' },
  { id: 310, text: "Tell the group your biggest sexual secret or take 4 shots.", nsfwLevel: 'Extreme' },
  { id: 311, text: "Describe the kinkiest thing you've done, or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 312, text: "Reveal your wildest sexual fantasy — or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 313, text: "Describe exactly what you'd do to {{randomOtherPlayer}} if you were alone — or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 314, text: "Tell the group your body count — anyone who guesses within 3 gets to give you a dare.", nsfwLevel: 'Extreme' },
  { id: 315, text: "If you've ever slept with anyone in this room, name them or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 316, text: "Describe how you like to be touched then let {{randomOtherPlayer}} try or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 317, text: "Whisper a dirty fantasy to {{randomOtherPlayer}} or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 318, text: "Whisper the last dirty text you sent into {{randomOtherPlayer}}'s ear.", nsfwLevel: 'Extreme' },
  { id: 319, text: "Whisper your dirtiest fantasy into {{randomOtherPlayer}}'s ear — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 320, text: "Let {{randomOtherPlayer}} whisper their dirtiest thought into your ear — or take 2 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Drink If (Sexual) ---
  { id: 321, text: "If you've had a threesome, take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 322, text: "If you've had sex outdoors, take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 323, text: "If you've ever joined the mile high club, take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 324, text: "If you've ever filmed yourself having sex, take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 325, text: "If you've had a one-night stand this year, remove one item of clothing.", nsfwLevel: 'Extreme' },
  { id: 326, text: "Remove one piece of clothing for each person here you've kissed.", nsfwLevel: 'Extreme' },

  // --- Extreme: Kissing ---
  { id: 327, text: "Start with a teasing kiss to {{randomOtherPlayer}} — just a peck — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 328, text: "Make out with {{randomOtherPlayer}} for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 329, text: "Make out with {{randomOtherPlayer}} for 30 seconds or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 330, text: "Full makeout session with {{randomOtherPlayer}} — or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 331, text: "French kiss {{randomOtherPlayer}} while the group watches.", nsfwLevel: 'Extreme' },
  { id: 332, text: "Pull {{randomOtherPlayer}} into a passionate kiss or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 333, text: "Kiss everyone in the room on the lips.", nsfwLevel: 'Extreme' },
  { id: 334, text: "Kiss any spot {{randomOtherPlayer}} chooses — or take 2 shots.", nsfwLevel: 'Extreme' },
  { id: 335, text: "Pick any body part on {{randomOtherPlayer}} and plant a long, wet kiss — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 336, text: "Let {{randomOtherPlayer}} kiss anywhere on your body they choose — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 337, text: "Hover your lips close to {{randomOtherPlayer}}'s without kissing for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 338, text: "Put an ice cube in your mouth and kiss {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 339, text: "Demonstrate on {{randomOtherPlayer}} how you like to be kissed — or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Kissing Body Parts ---
  { id: 340, text: "Kiss {{randomOtherPlayer}}'s neck for 15 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 341, text: "Let {{randomOtherPlayer}} bite or suck your neck or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 342, text: "Kiss {{randomOtherPlayer}}'s collarbone for 10 seconds — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 343, text: "Gently bite {{randomOtherPlayer}}'s earlobe — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 344, text: "Kiss {{randomOtherPlayer}}'s stomach for 10 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 345, text: "Kiss a trail down {{randomOtherPlayer}}'s stomach — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 346, text: "Kiss down the length of {{randomOtherPlayer}}'s spine — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 347, text: "Lick {{randomOtherPlayer}}'s inner thigh.", nsfwLevel: 'Extreme' },
  { id: 348, text: "Kiss {{randomOtherPlayer}}'s inner thighs — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 349, text: "Kiss from {{randomOtherPlayer}}'s ankle to their inner thigh or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 350, text: "Let {{randomOtherPlayer}} kiss your body (excluding genitals) for 1 minute or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 351, text: "Lie down and let {{randomOtherPlayer}} kiss their way down your body or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 352, text: "Lick or kiss any body part that {{randomOtherPlayer}} chooses no clothes in the way or drink 4 times.", nsfwLevel: 'Extreme' },
  { id: 353, text: "Crawl seductively to {{randomOtherPlayer}} and kiss their chest or drink 2 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Hickeys & Marking ---
  { id: 354, text: "Give {{randomOtherPlayer}} a hickey for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 355, text: "Leave a visible hickey on {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 356, text: "Let {{randomOtherPlayer}} leave a mark anywhere on your body — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 357, text: "Let {{randomOtherPlayer}} lightly mark you with a bite or hickey or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 358, text: "Let {{randomOtherPlayer}} leave a lipstick mark (or kiss mark) anywhere visible on your body — or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Licking & Sensual Touch ---
  { id: 359, text: "Lick {{randomOtherPlayer}}'s nipples for 10 seconds.", nsfwLevel: 'Extreme' },
  { id: 360, text: "Suck on {{randomOtherPlayer}}'s finger slowly.", nsfwLevel: 'Extreme' },
  { id: 361, text: "Let {{randomOtherPlayer}} suck on your fingers or drink 2 times.", nsfwLevel: 'Extreme' },
  { id: 362, text: "Suck on {{randomOtherPlayer}}'s toe or take 2 shots.", nsfwLevel: 'Extreme' },
  { id: 363, text: "Run your lips gently over any body part of {{randomOtherPlayer}} above the waist — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 364, text: "Run your lips gently over any body part of {{randomOtherPlayer}} below the waist — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 365, text: "Let {{randomOtherPlayer}} trace every inch of your body with their finger or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 366, text: "Slowly trace your fingertips across {{randomOtherPlayer}}'s bare ass — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 367, text: "Let {{randomOtherPlayer}} slowly slide their hand up your inner thigh or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 368, text: "Let {{randomOtherPlayer}} demonstrate on you how they like to be touched — or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Body Shots & Food Play ---
  { id: 369, text: "Take a body shot off {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 370, text: "Take a body shot off {{randomOtherPlayer}} — or take 2 shots yourself.", nsfwLevel: 'Extreme' },
  { id: 371, text: "Pour a shot into {{randomOtherPlayer}}'s belly button and drink it.", nsfwLevel: 'Extreme' },
  { id: 372, text: "Take a shot off {{randomOtherPlayer}}'s body — you pick the spot.", nsfwLevel: 'Extreme' },
  { id: 373, text: "Let {{randomOtherPlayer}} take a shot off your body — they pick the spot.", nsfwLevel: 'Extreme' },
  { id: 374, text: "Lick whipped cream off {{randomOtherPlayer}}'s neck.", nsfwLevel: 'Extreme' },
  { id: 375, text: "Lick whipped cream off any body part {{randomOtherPlayer}} chooses — or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 376, text: "Cover any body part you choose on {{randomOtherPlayer}} with whipped cream and lick it clean — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 377, text: "Let {{randomOtherPlayer}} lick whipped cream off your body or drink 3 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Ice Play ---
  { id: 378, text: "Put ice down your underwear for the next round.", nsfwLevel: 'Extreme' },
  { id: 379, text: "Use only your mouth to melt ice on {{randomOtherPlayer}}'s body — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 380, text: "Let {{randomOtherPlayer}} melt ice on your body using only their mouth — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 381, text: "Tease {{randomOtherPlayer}}'s nipples with ice — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 382, text: "Run an ice cube across {{randomOtherPlayer}}'s chest with your mouth — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 383, text: "Let {{randomOtherPlayer}} run an ice cube anywhere on your body with their mouth — or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Lap Dances & Grinding ---
  { id: 384, text: "Pick {{randomOtherPlayer}} to give you a lap dance.", nsfwLevel: 'Extreme' },
  { id: 385, text: "Give a full lap dance to {{randomOtherPlayer}} — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 386, text: "Receive a lap dance from {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 387, text: "Grind on {{randomOtherPlayer}} for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 388, text: "Let {{randomOtherPlayer}} grind on you for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 389, text: "Let {{randomOtherPlayer}} grind on you for 30 seconds or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 390, text: "Grind on {{randomOtherPlayer}}'s lap for one full song — or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 391, text: "Straddle {{randomOtherPlayer}} for 30 seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 392, text: "Sit on {{randomOtherPlayer}}'s lap for the next 5 rounds.", nsfwLevel: 'Extreme' },
  { id: 393, text: "Sit on {{randomOtherPlayer}}'s lap facing them for 1 minute or drink 3 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Stripping & Clothing Removal ---
  { id: 394, text: "Strip down to your underwear for the next 3 rounds.", nsfwLevel: 'Extreme' },
  { id: 395, text: "Flash the group or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 396, text: "Wear nothing but your underwear for the rest of the game.", nsfwLevel: 'Extreme' },
  { id: 397, text: "Strip completely naked for the next round or take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 398, text: "Strip down completely — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 399, text: "Remove any piece of clothing — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 400, text: "Let {{randomOtherPlayer}} remove any piece of your clothing — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 401, text: "Remove {{randomOtherPlayer}}'s top.", nsfwLevel: 'Extreme' },
  { id: 402, text: "Remove {{randomOtherPlayer}}'s pants using only your teeth.", nsfwLevel: 'Extreme' },
  { id: 403, text: "Use only your teeth to remove one piece of {{randomOtherPlayer}}'s clothing — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 404, text: "Remove any article of {{randomOtherPlayer}}'s clothing using only your teeth — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 405, text: "Have {{randomOtherPlayer}} remove your underwear using only their teeth or drink 4 times.", nsfwLevel: 'Extreme' },
  { id: 406, text: "Let {{randomOtherPlayer}} unhook your bra (or unzip your pants) with one hand or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 407, text: "Swap a piece of clothing with {{randomOtherPlayer}}.", nsfwLevel: 'Extreme' },
  { id: 408, text: "Swap underwear with {{randomOtherPlayer}} for the next 10 minutes.", nsfwLevel: 'Extreme' },
  { id: 409, text: "Swap underwear with {{randomOtherPlayer}} and wear it for 2 rounds or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 410, text: "Remove your underwear and toss it to {{randomOtherPlayer}} or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 411, text: "Go in the bathroom with {{randomOtherPlayer}} and swap one item of clothing or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 412, text: "{{randomOtherPlayer}} chooses: kiss them or lose an article of clothing.", nsfwLevel: 'Extreme' },

  // --- Extreme: Strip Teases ---
  { id: 413, text: "Give {{randomOtherPlayer}} a strip tease for one full song.", nsfwLevel: 'Extreme' },
  { id: 414, text: "Do a striptease for {{randomOtherPlayer}} or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 415, text: "Give {{randomOtherPlayer}} a private strip show to music or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 416, text: "Put on a sexy song and strip one article of clothing — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 417, text: "Put on a sexy song and let {{randomOtherPlayer}} remove one article of your clothing — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 418, text: "Have {{randomOtherPlayer}} undress you slowly, the way you describe or take 4 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Massage & Touch ---
  { id: 419, text: "Massage {{randomOtherPlayer}}'s inner thighs for 30 seconds.", nsfwLevel: 'Extreme' },
  { id: 420, text: "Give {{randomOtherPlayer}} a sensual massage above the waist for 1 minute — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 421, text: "Give {{randomOtherPlayer}} a deep massage below the waist for 1 minute — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 422, text: "Give {{randomOtherPlayer}} a 30-second massage anywhere below the waist (over clothes) — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 423, text: "Explore {{randomOtherPlayer}}'s body with your hands for 30 seconds — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 424, text: "Allow {{randomOtherPlayer}} to feel your chest or butt with both hands or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 425, text: "Let {{randomOtherPlayer}} grope your entire body for 1 minute or drink 4 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Spanking ---
  { id: 426, text: "Spank {{randomOtherPlayer}} — hard.", nsfwLevel: 'Extreme' },
  { id: 427, text: "Spank {{randomOtherPlayer}} hard for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 428, text: "Get spanked hard by {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 429, text: "Get spanked with a belt by {{randomOtherPlayer}} or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 430, text: "Let {{randomOtherPlayer}} spank you while you moan their name or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 431, text: "Let {{randomOtherPlayer}} pull your pants down and bite your butt or drink 3 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Nipple Play ---
  { id: 432, text: "Pinch {{randomOtherPlayer}}'s nipples — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 433, text: "Let {{randomOtherPlayer}} pinch your nipples — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 434, text: "Motorboat {{randomOtherPlayer}} — or take 2 shots.", nsfwLevel: 'Extreme' },

  // --- Extreme: Blindfold Play ---
  { id: 435, text: "Blindfold {{randomOtherPlayer}} and kiss them somewhere unexpected.", nsfwLevel: 'Extreme' },
  { id: 436, text: "Blindfold {{randomOtherPlayer}} and kiss them somewhere they won't expect — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 437, text: "Get blindfolded and allow {{randomOtherPlayer}} to touch you wherever they want for 15 seconds.", nsfwLevel: 'Extreme' },
  { id: 438, text: "Blindfold yourself and let {{randomOtherPlayer}} control you — or take 2 drinks.", nsfwLevel: 'Extreme' },
  { id: 439, text: "Be blindfolded while {{randomOtherPlayer}} explores your body for 60 seconds or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 440, text: "Get blindfolded. {{randomOtherPlayer}} does whatever they want to you for 30 seconds — or both take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Bondage & Restraints ---
  { id: 441, text: "Get handcuffed to a chair for the next 5 rounds.", nsfwLevel: 'Extreme' },
  { id: 442, text: "Let {{randomOtherPlayer}} tie you up with whatever's in the room.", nsfwLevel: 'Extreme' },
  { id: 443, text: "Tie {{randomOtherPlayer}} up completely — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 444, text: "Get tied up by {{randomOtherPlayer}} — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 445, text: "Tie {{randomOtherPlayer}} up and tease for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 446, text: "Get tied up by {{randomOtherPlayer}} and teased for 2 minutes — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 447, text: "Let {{randomOtherPlayer}} pin you to a wall or the floor or drink 3 times.", nsfwLevel: 'Extreme' },

  // --- Extreme: Control & Power Dynamics ---
  { id: 448, text: "Let {{randomOtherPlayer}} do whatever they want to you for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 449, text: "Do anything you want to {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 450, text: "{{randomOtherPlayer}} is your master for the next 3 rounds — you must do whatever they say or drink.", nsfwLevel: 'Extreme' },
  { id: 451, text: "Let the group dare you to do anything to {{randomOtherPlayer}} — majority rules.", nsfwLevel: 'Extreme' },
  { id: 452, text: "{{randomOtherPlayer}} gets to ask you any yes/no question — you must answer truthfully or strip.", nsfwLevel: 'Extreme' },

  // --- Extreme: Simulated Sex Acts ---
  { id: 453, text: "Simulate 69 position with {{randomOtherPlayer}} for 30 seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 454, text: "Simulate oral sex (clothed) on {{randomOtherPlayer}} for 15 seconds or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 455, text: "Simulate sex (clothed) with {{randomOtherPlayer}} for 30 seconds or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 456, text: "Recreate a sex scene with {{randomOtherPlayer}} or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 457, text: "Reenact your favorite porn scene with {{randomOtherPlayer}} or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 458, text: "Act out a sex fantasy with {{randomOtherPlayer}} (clothed or not) or drink 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 459, text: "Demonstrate your favorite sex position (fully clothed) or take 3 shots.", nsfwLevel: 'Extreme' },
  { id: 460, text: "Perform a fake orgasm for 10 seconds.", nsfwLevel: 'Extreme' },
  { id: 461, text: "Knock {{randomOtherPlayer}} over and 'accidentally' get busy for a few seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 462, text: "Have a one-minute hookup simulation with {{randomOtherPlayer}} or drink 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 463, text: "Simulate being on top of {{randomOtherPlayer}} while telling them what you'd do or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 464, text: "Pretend to give oral sex to a bottle while locking eyes with {{randomOtherPlayer}} or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 465, text: "Simulate fingering or oral on yourself while describing it to {{randomOtherPlayer}} or take 4 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Explicit Physical Contact ---
  { id: 466, text: "Let {{randomOtherPlayer}} put their hand down your pants for 10 seconds or take 3 drinks.", nsfwLevel: 'Extreme' },
  { id: 467, text: "Finger (or simulate) {{randomOtherPlayer}} under clothes for 15 seconds or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 468, text: "Strip completely and let {{randomOtherPlayer}} touch you anywhere but genitals for 60 seconds or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 469, text: "Get naked and lie down while {{randomOtherPlayer}} straddles you or drink 4 times.", nsfwLevel: 'Extreme' },
  { id: 470, text: "Let {{randomOtherPlayer}} lie on top of you shirtless for 30 seconds or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 471, text: "Sit naked while {{randomOtherPlayer}} gives you compliments on each body part or drink 3 times.", nsfwLevel: 'Extreme' },
  { id: 472, text: "Dare: {{randomOtherPlayer}} must remove your pants and feel inside your underwear.", nsfwLevel: 'Extreme' },

  // --- Extreme: Toys ---
  { id: 473, text: "Use a toy of {{randomOtherPlayer}}'s choice on yourself for 30 seconds — or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 474, text: "Use a toy of your choice on {{randomOtherPlayer}} for 30 seconds — or take 3 drinks.", nsfwLevel: 'Extreme' },

  // --- Extreme: Phone & External ---
  { id: 475, text: "Call your last hookup and say 'I miss your body' or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 476, text: "Show the group the last nude you received (or take 5 drinks).", nsfwLevel: 'Extreme' },
  { id: 477, text: "Take a naked selfie (not shared) or finish your drink.", nsfwLevel: 'Extreme' },
  { id: 478, text: "Let {{randomOtherPlayer}} draw something on your chest — clothing off.", nsfwLevel: 'Extreme' },

  // --- Extreme: Group Activities ---
  { id: 479, text: "Everyone removes one article of clothing. Last person to do so finishes their drink.", nsfwLevel: 'Extreme' },
  { id: 480, text: "Spin a bottle — whoever it lands on, you have to make out with for 20 seconds.", nsfwLevel: 'Extreme' },
  { id: 481, text: "Seven minutes in heaven with {{randomOtherPlayer}} — or both take 5 drinks.", nsfwLevel: 'Extreme' },
  { id: 482, text: "Go into a private room with {{randomOtherPlayer}} for 3 minutes or take 4 drinks.", nsfwLevel: 'Extreme' },
  { id: 483, text: "Wild Card: Skip this prompt and take {{randomOtherPlayer}} somewhere private for 2 minutes — or both finish your drinks.", nsfwLevel: 'Extreme' },
  { id: 484, text: "Hookup with {{randomOtherPlayer}} or take 3 drinks.", nsfwLevel: 'Extreme' }
];